// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AircraftRecord struct {
	CorrelationId string `json:"correlationId"`
	Country       string `json:"country"`
	Hex           string `json:"hex"`
	Manufacturer  string `json:"manufacturer"`
	Model         string `json:"model"`
	Owner         string `json:"owner"`
	Status        string `json:"status"`
	Tail          string `json:"tail"`
	Type          string `json:"type"`
	Valid         bool   `json:"valid"`
	Year          int    `json:"year"`
}

type ErrorResponse struct {
	CorrelationId string `json:"correlationId"`
	Error         string `json:"error"`
	Service       string `json:"service"`
}

type GenericSuccess struct {
	Cached        bool            `json:"cached"`
	CorrelationId string          `json:"correlationId"`
	Data          json.RawMessage `json:"data"`
}
