// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Hand-authored (not generated): ctx-attached HTTP client for MCP tool
// handlers. Generated handlers in tools.go pull *client.Client from ctx
// via clientFromContext() instead of constructing one inline. Each
// transport binary is responsible for populating ctx in its server's
// context hook:
//
//	stdio  → server.WithStdioContextFunc(...) loads disk config once at
//	         startup and reuses one client for every tool call.
//	http   → server.WithHTTPContextFunc(...) reads the Authorization
//	         header on each request and builds a per-user client.
//
// REGENERATION NOTE: tools.go is generated by cli-printing-press and
// contains a small hand-applied patch inside makeAPIHandler that calls
// clientFromContext(ctx) instead of the historical newMCPClient(). If
// cli-printing-press regenerates tools.go, re-apply that patch (or
// teach the generator about ctx-based client wiring upstream).

package mcp

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/datpaq/mcp/internal/client"
	"github.com/datpaq/mcp/internal/config"
)

type clientCtxKey struct{}

// ContextWithClient attaches an HTTP client to ctx for downstream MCP
// tool handlers to use. Transport binaries call this from their server's
// context hook.
func ContextWithClient(ctx context.Context, c *client.Client) context.Context {
	return context.WithValue(ctx, clientCtxKey{}, c)
}

// clientFromContext returns the ctx-attached client, or nil if none.
// Handlers must check for nil and return a clear error to the caller.
func clientFromContext(ctx context.Context) *client.Client {
	c, _ := ctx.Value(clientCtxKey{}).(*client.Client)
	return c
}

// NewDiskConfigClient builds the client used by the local stdio MCP
// binary, loading credentials from ~/.config/datpaq/config.toml. The
// hosted HTTP binary does not call this — it constructs per-request
// clients from inbound API keys.
//
// NoCache is forced on: agents calling through MCP need fresh data
// every call, and the on-disk response cache survives across MCP
// server invocations (so a DELETE/PATCH followed by a GET would
// otherwise return the pre-mutation snapshot for up to the cache TTL).
func NewDiskConfigClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "datpaq", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	c.NoCache = true
	return c, nil
}
