// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
//
// HAND-EDIT (see context.go): makeAPIHandler pulls the API client from
// ctx via clientFromContext(...) instead of constructing one inline.
// On regeneration, re-apply that small change or the stdio and HTTP
// transports both lose access to their per-binary client.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/datpaq/mcp/internal/cli"
	"github.com/datpaq/mcp/internal/client"
	"github.com/datpaq/mcp/internal/cliutil"
	"github.com/datpaq/mcp/internal/mcp/cobratree"
	"github.com/datpaq/mcp/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("aircraft_batch-lookup",
			mcplib.WithDescription("Batch aircraft lookups by tail number. Required: tails. Returns the new GenericSuccess."),
			mcplib.WithString("tails", mcplib.Required(), mcplib.Description("Tails")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/aircraft/batch", false, nil, []mcpParamBinding{{PublicName: "tails", WireName: "tails", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("aircraft_lookup-by-icao",
			mcplib.WithDescription("Look up aircraft by ICAO hex code. Required: hex. Returns the AircraftRecord."),
			mcplib.WithString("hex", mcplib.Required(), mcplib.Description("6-character ICAO hexadecimal transponder code")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/aircraft/icao/{hex}", false, nil, []mcpParamBinding{{PublicName: "hex", WireName: "hex", Location: "path"}}, []string{"hex"}),
	)
	s.AddTool(
		mcplib.NewTool("aircraft_lookup-by-tail",
			mcplib.WithDescription("Returns aircraft ownership, manufacturer, model, type, and year from the FAA registry using an N-number (tail number). Required: tail."),
			mcplib.WithString("tail", mcplib.Required(), mcplib.Description("FAA tail/N-number (e.g. N12345)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/aircraft/lookup", false, nil, []mcpParamBinding{{PublicName: "tail", WireName: "tail", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("aircraft_lookup-by-type",
			mcplib.WithDescription("Look up aircraft type specifications. Required: code. Returns the GenericSuccess."),
			mcplib.WithString("code", mcplib.Required(), mcplib.Description("Aircraft type designator code (ICAO, e.g. B737, C172)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/aircraft/type/{code}", false, nil, []mcpParamBinding{{PublicName: "code", WireName: "code", Location: "path"}}, []string{"code"}),
	)
	s.AddTool(
		mcplib.NewTool("company-enrichment_company-enrich",
			mcplib.WithDescription("Returns structured company data including industry, size, social profiles, and contact information. Provide company_name, domain, or both. Optional: company_name, domain."),
			mcplib.WithString("company_name", mcplib.Description("Company name")),
			mcplib.WithString("domain", mcplib.Description("Domain")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/company-enrichment/enrich", false, nil, []mcpParamBinding{{PublicName: "company_name", WireName: "company_name", Location: "body"}, {PublicName: "domain", WireName: "domain", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("convert-time_convert_time",
			mcplib.WithDescription("Converts a datetime value from a source timezone to a target timezone. Accepts ISO 8601 strings, Unix epoch timestamps, or omit sourceTime to convert the current time. Required: sourceZone, targetZone. Optional: sourceTime. Returns the GenericSuccess."),
			mcplib.WithString("sourceTime", mcplib.Description("Time to convert (ISO 8601 or Unix ms). Defaults to current time.")),
			mcplib.WithString("sourceZone", mcplib.Required(), mcplib.Description("Source IANA timezone identifier")),
			mcplib.WithString("targetZone", mcplib.Required(), mcplib.Description("Target IANA timezone identifier")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/convert-time", false, nil, []mcpParamBinding{{PublicName: "sourceTime", WireName: "sourceTime", Location: "query"}, {PublicName: "sourceZone", WireName: "sourceZone", Location: "query"}, {PublicName: "targetZone", WireName: "targetZone", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("country-codes_country-by-iso",
			mcplib.WithDescription("Get a country by ISO 2 or ISO 3 code. Required: iso. Returns the GenericSuccess."),
			mcplib.WithString("iso", mcplib.Required(), mcplib.Description("ISO 3166-1 alpha-2 or alpha-3 code")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/country-codes/countries/{iso}", false, nil, []mcpParamBinding{{PublicName: "iso", WireName: "iso", Location: "path"}}, []string{"iso"}),
	)
	s.AddTool(
		mcplib.NewTool("country-codes_country-export",
			mcplib.WithDescription("Export country data in bulk. Optional: format (default: json). Returns the GenericSuccess."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/country-codes/export", false, nil, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("country-codes_country-list",
			mcplib.WithDescription("List all countries with ISO codes and metadata. Returns the GenericSuccess."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/country-codes/countries", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("country-codes_country-search",
			mcplib.WithDescription("Search countries by full or partial name. Required: name. Returns the GenericSuccess."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/country-codes/countries/search", false, nil, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("current-time_current_time",
			mcplib.WithDescription("Returns the current date/time with UTC offset and DST status for a given timezone. Required: target."),
			mcplib.WithString("target", mcplib.Required(), mcplib.Description("IANA timezone identifier (e.g. America/New_York, UTC, Asia/Tokyo)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/current-time", false, nil, []mcpParamBinding{{PublicName: "target", WireName: "target", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("define_dictionary",
			mcplib.WithDescription("Returns definitions, part of speech, pronunciation, and etymology for the given word. Required: word. Optional: include_pronunciation (default: false)."),
			mcplib.WithBoolean("include_pronunciation", mcplib.Description("Include pronunciation")),
			mcplib.WithString("word", mcplib.Required(), mcplib.Description("Word")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/define", false, nil, []mcpParamBinding{{PublicName: "include_pronunciation", WireName: "include_pronunciation", Location: "body"}, {PublicName: "word", WireName: "word", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("dns_lookup",
			mcplib.WithDescription("Supports record types A, AAAA, MX, CNAME, TXT, NS, SOA, and ALL. Required: domain. Optional: type (default: A). Returns the GenericSuccess."),
			mcplib.WithString("domain", mcplib.Required(), mcplib.Description("Domain")),
			mcplib.WithString("type", mcplib.Description("DNS record type. Defaults to A.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/dns", false, nil, []mcpParamBinding{{PublicName: "domain", WireName: "domain", Location: "query"}, {PublicName: "type", WireName: "type", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("domain-lookup_get",
			mcplib.WithDescription("Check domain availability and registration info. Required: domain. Optional: include_registration, include_expiry, tlds. Returns the GenericSuccess."),
			mcplib.WithString("domain", mcplib.Required(), mcplib.Description("Domain")),
			mcplib.WithBoolean("include_registration", mcplib.Description("Include registration")),
			mcplib.WithBoolean("include_expiry", mcplib.Description("Include expiry")),
			mcplib.WithString("tlds", mcplib.Description("Comma-separated TLDs to check (e.g. com,net,org)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/domain-lookup", false, nil, []mcpParamBinding{{PublicName: "domain", WireName: "domain", Location: "query"}, {PublicName: "include_registration", WireName: "include_registration", Location: "query"}, {PublicName: "include_expiry", WireName: "include_expiry", Location: "query"}, {PublicName: "tlds", WireName: "tlds", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("domain-lookup_post",
			mcplib.WithDescription("Check domain availability (POST). Required: domain. Optional: tlds. Returns the new GenericSuccess."),
			mcplib.WithString("domain", mcplib.Required(), mcplib.Description("Domain")),
			mcplib.WithString("tlds", mcplib.Description("Tlds")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/domain-lookup/lookup", false, nil, []mcpParamBinding{{PublicName: "domain", WireName: "domain", Location: "body"}, {PublicName: "tlds", WireName: "tlds", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("email-validation_email-validate-batch",
			mcplib.WithDescription("Validate multiple email addresses. Required: emails. Returns the new GenericSuccess."),
			mcplib.WithString("emails", mcplib.Required(), mcplib.Description("Emails")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/email-validation/validate-batch", false, nil, []mcpParamBinding{{PublicName: "emails", WireName: "emails", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("email-validation_email-validate-single",
			mcplib.WithDescription("Checks email format, domain MX records, and optional deliverability. Detects disposable/temporary address providers. Required: email. Optional: include_details (default: false). Returns the new GenericSuccess."),
			mcplib.WithString("email", mcplib.Required(), mcplib.Description("Email")),
			mcplib.WithBoolean("include_details", mcplib.Description("Include details")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/email-validation/validate", false, nil, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "body"}, {PublicName: "include_details", WireName: "include_details", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ev-charger_ev-networks",
			mcplib.WithDescription("List all supported charging networks. Returns the GenericSuccess."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ev-charger/networks", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ev-charger_ev-station-by-id",
			mcplib.WithDescription("Get specific charging station by ID. Required: id. Returns the GenericSuccess."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ev-charger/stations/{id}", false, nil, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("ev-charger_ev-station-status",
			mcplib.WithDescription("Get real-time station status. Required: id. Returns the GenericSuccess."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ev-charger/status/{id}", false, nil, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("ev-charger_ev-stations-by-address",
			mcplib.WithDescription("Search EV charging stations by address. Required: address. Returns the GenericSuccess."),
			mcplib.WithString("address", mcplib.Required(), mcplib.Description("Address")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ev-charger/stations/search", false, nil, []mcpParamBinding{{PublicName: "address", WireName: "address", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ev-charger_ev-stations-by-coords",
			mcplib.WithDescription("Find EV charging stations near coordinates. Required: lat, lon. Optional: radius (default: 5). Returns the GenericSuccess."),
			mcplib.WithNumber("lat", mcplib.Required(), mcplib.Description("Latitude (-90 to 90)")),
			mcplib.WithNumber("lon", mcplib.Required(), mcplib.Description("Longitude (-180 to 180)")),
			mcplib.WithNumber("radius", mcplib.Description("Search radius in miles (max 100, default 5)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ev-charger/stations", false, nil, []mcpParamBinding{{PublicName: "lat", WireName: "lat", Location: "query"}, {PublicName: "lon", WireName: "lon", Location: "query"}, {PublicName: "radius", WireName: "radius", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("exchange-rates-and-currency_exchange-rate-bulk",
			mcplib.WithDescription("Batch currency conversions. Required: conversions. Returns the new GenericSuccess."),
			mcplib.WithString("conversions", mcplib.Required(), mcplib.Description("Conversions")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/exchange-rates-and-currency/api/bulk-exchange", false, nil, []mcpParamBinding{{PublicName: "conversions", WireName: "conversions", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("exchange-rates-and-currency_exchange-rate-get",
			mcplib.WithDescription("Returns the current exchange rate between two currencies. Provide an amount to perform conversion. Supports fiat (ISO 4217) and crypto (BTC, ETH). Required: from, to. Optional: amount."),
			mcplib.WithString("from", mcplib.Required(), mcplib.Description("Source currency code (e.g. USD) or crypto symbol (e.g. BTC)")),
			mcplib.WithString("to", mcplib.Required(), mcplib.Description("Target currency code")),
			mcplib.WithNumber("amount", mcplib.Description("Amount to convert. Omit to retrieve rate only.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/exchange-rates-and-currency/api/exchange", false, nil, []mcpParamBinding{{PublicName: "from", WireName: "from", Location: "query"}, {PublicName: "to", WireName: "to", Location: "query"}, {PublicName: "amount", WireName: "amount", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("generate_sample-data-post",
			mcplib.WithDescription("Generate realistic mock data using a JSON request body. Recommended for full control over type, count, fields, and format. Required: type. Optional: count (default: 1), fields, format (default: json). Returns the new GenericSuccess."),
			mcplib.WithNumber("count", mcplib.Description("Count")),
			mcplib.WithString("fields", mcplib.Description("Optional field names to include.")),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("type", mcplib.Required(), mcplib.Description("Schema type to generate, such as user, company, product, or transaction.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/generate", false, nil, []mcpParamBinding{{PublicName: "count", WireName: "count", Location: "body"}, {PublicName: "fields", WireName: "fields", Location: "body"}, {PublicName: "format", WireName: "format", Location: "body"}, {PublicName: "type", WireName: "type", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("generate-batch_sample-data-post",
			mcplib.WithDescription("Submit multiple sample-data generation requests in one call. Required: requests. Returns the new GenericSuccess."),
			mcplib.WithString("requests", mcplib.Required(), mcplib.Description("Requests")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/generate-batch", false, nil, []mcpParamBinding{{PublicName: "requests", WireName: "requests", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("helicopter_lookup-by-icao",
			mcplib.WithDescription("Look up helicopter by ICAO hex code. Required: hex. Returns the GenericSuccess."),
			mcplib.WithString("hex", mcplib.Required(), mcplib.Description("Hex")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/helicopter/icao/{hex}", false, nil, []mcpParamBinding{{PublicName: "hex", WireName: "hex", Location: "path"}}, []string{"hex"}),
	)
	s.AddTool(
		mcplib.NewTool("helicopter_lookup-by-registration",
			mcplib.WithDescription("Look up helicopter by registration number. Required: registration. Returns the GenericSuccess."),
			mcplib.WithString("registration", mcplib.Required(), mcplib.Description("Registration")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/helicopter/lookup", false, nil, []mcpParamBinding{{PublicName: "registration", WireName: "registration", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("helicopter_lookup-by-serial",
			mcplib.WithDescription("Look up helicopter by manufacturer serial number. Required: serial. Returns the GenericSuccess."),
			mcplib.WithString("serial", mcplib.Required(), mcplib.Description("Serial")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/helicopter/serial/{serial}", false, nil, []mcpParamBinding{{PublicName: "serial", WireName: "serial", Location: "path"}}, []string{"serial"}),
	)
	s.AddTool(
		mcplib.NewTool("helicopter_manufacturers",
			mcplib.WithDescription("List helicopter manufacturers. Returns the GenericSuccess."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/helicopter/manufacturers", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("image-processing_image-compress",
			mcplib.WithDescription("Compress an image. Required: image_url. Optional: quality."),
			mcplib.WithString("image_url", mcplib.Required(), mcplib.Description("Image url")),
			mcplib.WithNumber("quality", mcplib.Description("Quality")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/image-processing/compress", true, map[string]string{"Accept": "image/jpeg"}, []mcpParamBinding{{PublicName: "image_url", WireName: "image_url", Location: "body"}, {PublicName: "quality", WireName: "quality", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("image-processing_image-convert",
			mcplib.WithDescription("Convert image to a different format. Required: format, image_url."),
			mcplib.WithString("format", mcplib.Required(), mcplib.Description("Format")),
			mcplib.WithString("image_url", mcplib.Required(), mcplib.Description("Image url")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/image-processing/convert", true, map[string]string{"Accept": "image/jpeg"}, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "body"}, {PublicName: "image_url", WireName: "image_url", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("image-processing_image-crop",
			mcplib.WithDescription("Crop an image to a region. Required: height, image_url, width, x, y."),
			mcplib.WithNumber("height", mcplib.Required(), mcplib.Description("Height")),
			mcplib.WithString("image_url", mcplib.Required(), mcplib.Description("Image url")),
			mcplib.WithNumber("width", mcplib.Required(), mcplib.Description("Width")),
			mcplib.WithNumber("x", mcplib.Required(), mcplib.Description("X")),
			mcplib.WithNumber("y", mcplib.Required(), mcplib.Description("Y")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/image-processing/crop", true, map[string]string{"Accept": "image/jpeg"}, []mcpParamBinding{{PublicName: "height", WireName: "height", Location: "body"}, {PublicName: "image_url", WireName: "image_url", Location: "body"}, {PublicName: "width", WireName: "width", Location: "body"}, {PublicName: "x", WireName: "x", Location: "body"}, {PublicName: "y", WireName: "y", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("image-processing_image-metadata",
			mcplib.WithDescription("Extract metadata from an image. Required: image_url. Returns the new GenericSuccess."),
			mcplib.WithString("image_url", mcplib.Required(), mcplib.Description("Image url")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/image-processing/metadata", false, nil, []mcpParamBinding{{PublicName: "image_url", WireName: "image_url", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("image-processing_image-pipeline",
			mcplib.WithDescription("Executes an ordered array of image operations in a single request. Recommended over individual endpoints when multiple operations are needed. Supports resize, compress, convert, crop, and metadata. Required: image_url, operations."),
			mcplib.WithString("image_url", mcplib.Required(), mcplib.Description("Image url")),
			mcplib.WithString("operations", mcplib.Required(), mcplib.Description("Operations")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/image-processing/process", true, map[string]string{"Accept": "image/jpeg"}, []mcpParamBinding{{PublicName: "image_url", WireName: "image_url", Location: "body"}, {PublicName: "operations", WireName: "operations", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("image-processing_image-resize",
			mcplib.WithDescription("Resize an image to specified dimensions. Required: image_url. Optional: fit (default: cover), height, width."),
			mcplib.WithString("fit", mcplib.Description("Fit")),
			mcplib.WithNumber("height", mcplib.Description("Height")),
			mcplib.WithString("image_url", mcplib.Required(), mcplib.Description("Image url")),
			mcplib.WithNumber("width", mcplib.Description("Width")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/image-processing/resize", true, map[string]string{"Accept": "image/jpeg"}, []mcpParamBinding{{PublicName: "fit", WireName: "fit", Location: "body"}, {PublicName: "height", WireName: "height", Location: "body"}, {PublicName: "image_url", WireName: "image_url", Location: "body"}, {PublicName: "width", WireName: "width", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("image-processing_info",
			mcplib.WithDescription("Returns supported image operations, formats, and service metadata."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/image-processing", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ip-geolocation_batch",
			mcplib.WithDescription("Batch IP geolocation lookup. Required: ips. Returns the new GenericSuccess."),
			mcplib.WithString("ips", mcplib.Required(), mcplib.Description("Ips")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ip-geolocation/batch", false, nil, []mcpParamBinding{{PublicName: "ips", WireName: "ips", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ip-geolocation_get",
			mcplib.WithDescription("Returns country, region, city, coordinates, ISP, ASN, and timezone for any IPv4 or IPv6 address. Required: ip."),
			mcplib.WithString("ip", mcplib.Required(), mcplib.Description("Ip")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ip-geolocation", false, nil, []mcpParamBinding{{PublicName: "ip", WireName: "ip", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ip-geolocation_post",
			mcplib.WithDescription("Get geographic location for an IP address (POST). Required: ip. Returns the new GenericSuccess."),
			mcplib.WithString("ip", mcplib.Required(), mcplib.Description("Ip")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ip-geolocation", false, nil, []mcpParamBinding{{PublicName: "ip", WireName: "ip", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ip-intelligence_batch",
			mcplib.WithDescription("Batch IP threat intelligence lookup. Required: ips. Returns the new GenericSuccess."),
			mcplib.WithString("ips", mcplib.Required(), mcplib.Description("Ips")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ip-intelligence/batch", false, nil, []mcpParamBinding{{PublicName: "ips", WireName: "ips", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ip-intelligence_batch-info",
			mcplib.WithDescription("Returns batch processing limits, example request shape, and response schema details."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ip-intelligence/batch/info", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ip-intelligence_get",
			mcplib.WithDescription("Returns trust score, risk classification, VPN/proxy/Tor detection, datacenter detection, and threat categories. Omit the ip parameter to analyze the caller's IP. Optional: ip."),
			mcplib.WithString("ip", mcplib.Description("IP to analyze. Omits to use the caller's IP.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ip-intelligence", false, nil, []mcpParamBinding{{PublicName: "ip", WireName: "ip", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("mac-address_lookup",
			mcplib.WithDescription("Lookup vendor by full MAC address, 6-character OUI prefix, or organization name. Provide exactly one of the three parameters. Optional: mac, prefix, org. Returns the GenericSuccess."),
			mcplib.WithString("mac", mcplib.Description("Full MAC address (XX:XX:XX:XX:XX:XX or XX-XX-XX-XX-XX-XX)")),
			mcplib.WithString("prefix", mcplib.Description("6-character hex OUI prefix")),
			mcplib.WithString("org", mcplib.Description("Organization name search (min 2 chars)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mac-address", false, nil, []mcpParamBinding{{PublicName: "mac", WireName: "mac", Location: "query"}, {PublicName: "prefix", WireName: "prefix", Location: "query"}, {PublicName: "org", WireName: "org", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("mx-lookup_batch",
			mcplib.WithDescription("Batch MX record lookup for multiple domains. Required: domains. Returns the new GenericSuccess."),
			mcplib.WithString("domains", mcplib.Required(), mcplib.Description("Domains")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/mx-lookup/batch", false, nil, []mcpParamBinding{{PublicName: "domains", WireName: "domains", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("mx-lookup_get",
			mcplib.WithDescription("Returns mail exchange records with optional IP resolution, SMTP testing, and SPF extraction. Required: domain. Optional: resolve_ips (default: false), test_smtp (default: false), include_spf (default: false)."),
			mcplib.WithString("domain", mcplib.Required(), mcplib.Description("Domain")),
			mcplib.WithBoolean("resolve_ips", mcplib.Description("Resolve ips")),
			mcplib.WithBoolean("test_smtp", mcplib.Description("Test smtp")),
			mcplib.WithBoolean("include_spf", mcplib.Description("Include spf")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/mx-lookup", false, nil, []mcpParamBinding{{PublicName: "domain", WireName: "domain", Location: "query"}, {PublicName: "resolve_ips", WireName: "resolve_ips", Location: "query"}, {PublicName: "test_smtp", WireName: "test_smtp", Location: "query"}, {PublicName: "include_spf", WireName: "include_spf", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("mx-lookup_post",
			mcplib.WithDescription("Look up MX records for a domain (POST). Required: domain. Optional: include_spf (default: false), resolve_ips (default: false), test_smtp (default: false). Returns the new GenericSuccess."),
			mcplib.WithString("domain", mcplib.Required(), mcplib.Description("Domain")),
			mcplib.WithBoolean("include_spf", mcplib.Description("Include spf")),
			mcplib.WithBoolean("resolve_ips", mcplib.Description("Resolve ips")),
			mcplib.WithBoolean("test_smtp", mcplib.Description("Test smtp")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/mx-lookup/lookup", false, nil, []mcpParamBinding{{PublicName: "domain", WireName: "domain", Location: "body"}, {PublicName: "include_spf", WireName: "include_spf", Location: "body"}, {PublicName: "resolve_ips", WireName: "resolve_ips", Location: "body"}, {PublicName: "test_smtp", WireName: "test_smtp", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("precious-metals_assets",
			mcplib.WithDescription("Returns metadata for all supported assets — gold (XAU), silver (XAG), palladium (XPD), copper, BTC, ETH, etc."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/precious-metals/assets", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("precious-metals_history",
			mcplib.WithDescription("Get historical price data for an asset. Required: symbol (default: XAU). Optional: from, to. Returns the GenericSuccess."),
			mcplib.WithString("symbol", mcplib.Required(), mcplib.Description("Asset symbol")),
			mcplib.WithString("from", mcplib.Description("From")),
			mcplib.WithString("to", mcplib.Description("To")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/precious-metals/history/{symbol}", false, nil, []mcpParamBinding{{PublicName: "symbol", WireName: "symbol", Location: "path"}, {PublicName: "from", WireName: "from", Location: "query"}, {PublicName: "to", WireName: "to", Location: "query"}}, []string{"symbol"}),
	)
	s.AddTool(
		mcplib.NewTool("precious-metals_prices",
			mcplib.WithDescription("Get current prices for precious metals and crypto. Optional: symbol, currency (default: USD). Returns the GenericSuccess."),
			mcplib.WithString("symbol", mcplib.Description("Asset symbol (e.g. XAU, XAG, BTC). Returns all assets if omitted.")),
			mcplib.WithString("currency", mcplib.Description("Quote currency (ISO 4217, default USD)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/precious-metals/prices", false, nil, []mcpParamBinding{{PublicName: "symbol", WireName: "symbol", Location: "query"}, {PublicName: "currency", WireName: "currency", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("profanity_analyze",
			mcplib.WithDescription("Comprehensive profanity analysis with severity and word positions. Required: text. Returns the GenericSuccess."),
			mcplib.WithString("text", mcplib.Required(), mcplib.Description("Text")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/profanity/analyze", false, nil, []mcpParamBinding{{PublicName: "text", WireName: "text", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("profanity_detect",
			mcplib.WithDescription("Detect whether text contains profanity. Required: text. Returns the GenericSuccess."),
			mcplib.WithString("text", mcplib.Required(), mcplib.Description("Text")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/profanity/detect", false, nil, []mcpParamBinding{{PublicName: "text", WireName: "text", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("profanity_filter",
			mcplib.WithDescription("Replaces profane words with asterisks. Returns cleaned text. Required: text."),
			mcplib.WithString("text", mcplib.Required(), mcplib.Description("Text")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/profanity/filter", false, nil, []mcpParamBinding{{PublicName: "text", WireName: "text", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("public-holidays_countries",
			mcplib.WithDescription("List all supported countries for holiday data. Returns the GenericSuccess."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/public-holidays/countries", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("public-holidays_public_holidays",
			mcplib.WithDescription("Accepts ISO-2, ISO-3, or full country names. Returns holidays with ISO, US, and EU date formats. Filter by year and/or month. Required: country. Optional: year, month."),
			mcplib.WithString("country", mcplib.Required(), mcplib.Description("Country code (ISO-2/ISO-3) or full name")),
			mcplib.WithNumber("year", mcplib.Description("Year")),
			mcplib.WithNumber("month", mcplib.Description("Month")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/public-holidays", false, nil, []mcpParamBinding{{PublicName: "country", WireName: "country", Location: "query"}, {PublicName: "year", WireName: "year", Location: "query"}, {PublicName: "month", WireName: "month", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sample-data_batch-get",
			mcplib.WithDescription("Generates mock data using Faker.js. Supports 20+ schema types including user, person, address, company, product, and more. Use the requests parameter as a JSON-encoded array. Required: requests. Returns the GenericSuccess."),
			mcplib.WithString("requests", mcplib.Required(), mcplib.Description("JSON-encoded array of generation requests [{type, count, fields?}]")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/sample-data/batch", false, nil, []mcpParamBinding{{PublicName: "requests", WireName: "requests", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sample-data_batch-post",
			mcplib.WithDescription("Generate multiple types of sample data (POST). Required: requests. Returns the new GenericSuccess."),
			mcplib.WithString("requests", mcplib.Required(), mcplib.Description("Requests")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/sample-data/batch", false, nil, []mcpParamBinding{{PublicName: "requests", WireName: "requests", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sample-data_generate-get",
			mcplib.WithDescription("GET-compatible sample data generation endpoint for scripts and browser testing. Required: type. Optional: count (default: 1), fields, format (default: json). Returns the GenericSuccess."),
			mcplib.WithString("type", mcplib.Required(), mcplib.Description("Schema type to generate, such as user, company, product, or transaction.")),
			mcplib.WithNumber("count", mcplib.Description("Number of records to generate.")),
			mcplib.WithString("fields", mcplib.Description("Comma-separated list of fields to include.")),
			mcplib.WithString("format", mcplib.Description("Response format.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/sample-data", false, nil, []mcpParamBinding{{PublicName: "type", WireName: "type", Location: "query"}, {PublicName: "count", WireName: "count", Location: "query"}, {PublicName: "fields", WireName: "fields", Location: "query"}, {PublicName: "format", WireName: "format", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("schemas_sample-data",
			mcplib.WithDescription("Returns all available sample-data schema names with default field lists."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/schemas", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("secure-relay_custom",
			mcplib.WithDescription("Legacy relay endpoint with extended configuration options for custom header injection and response transformation. Required: method, url. Optional: body, headers. Returns the new GenericSuccess."),
			mcplib.WithString("body", mcplib.Description("Body")),
			mcplib.WithString("headers", mcplib.Description("Headers")),
			mcplib.WithString("method", mcplib.Required(), mcplib.Description("Method")),
			mcplib.WithString("url", mcplib.Required(), mcplib.Description("Url")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/secure-relay/custom", false, nil, []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "body"}, {PublicName: "headers", WireName: "headers", Location: "body"}, {PublicName: "method", WireName: "method", Location: "body"}, {PublicName: "url", WireName: "url", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("secure-relay_relay",
			mcplib.WithDescription("Forwards HTTP requests to HTTPS targets with no server-side storage. Requests must include HMAC-SHA256 signature headers for verification. Supports replay attack protection via timestamp validation. Required: method, url. Optional: body, headers. Returns the new GenericSuccess."),
			mcplib.WithString("body", mcplib.Description("Request body for POST/PUT/PATCH requests")),
			mcplib.WithString("headers", mcplib.Description("Additional headers to include in the relayed request")),
			mcplib.WithString("method", mcplib.Required(), mcplib.Description("Method")),
			mcplib.WithString("url", mcplib.Required(), mcplib.Description("Target HTTPS URL")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/secure-relay/relay", false, nil, []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "body"}, {PublicName: "headers", WireName: "headers", Location: "body"}, {PublicName: "method", WireName: "method", Location: "body"}, {PublicName: "url", WireName: "url", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("spell-check_batch",
			mcplib.WithDescription("Spell check multiple texts. Required: texts. Optional: language (default: en). Returns the new GenericSuccess."),
			mcplib.WithString("language", mcplib.Description("Language")),
			mcplib.WithString("texts", mcplib.Required(), mcplib.Description("Texts")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/spell-check/batch", false, nil, []mcpParamBinding{{PublicName: "language", WireName: "language", Location: "body"}, {PublicName: "texts", WireName: "texts", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("spell-check_languages",
			mcplib.WithDescription("List supported languages for spell checking. Returns the GenericSuccess."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/spell-check/languages", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("spell-check_spell_check",
			mcplib.WithDescription("Detects spelling errors with ranked correction suggestions. Supports English, Spanish, French, German, and Italian. Also catches grammar patterns such as repeated words and spacing errors. Required: text. Optional: language (default: en). Returns the new GenericSuccess."),
			mcplib.WithString("language", mcplib.Description("Language")),
			mcplib.WithString("text", mcplib.Required(), mcplib.Description("Text")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/spell-check", false, nil, []mcpParamBinding{{PublicName: "language", WireName: "language", Location: "body"}, {PublicName: "text", WireName: "text", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("states_by-abbr",
			mcplib.WithDescription("Get U.S. state by 2-letter abbreviation. Required: abbr. Returns the GenericSuccess."),
			mcplib.WithString("abbr", mcplib.Required(), mcplib.Description("2-letter state abbreviation")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/states/states/{abbr}", false, nil, []mcpParamBinding{{PublicName: "abbr", WireName: "abbr", Location: "path"}}, []string{"abbr"}),
	)
	s.AddTool(
		mcplib.NewTool("states_by-fips",
			mcplib.WithDescription("Get U.S. state by FIPS code. Required: fipscode. Returns the GenericSuccess."),
			mcplib.WithString("fipscode", mcplib.Required(), mcplib.Description("2-digit FIPS state code")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/states/fips/{fipscode}", false, nil, []mcpParamBinding{{PublicName: "fipscode", WireName: "fipscode", Location: "path"}}, []string{"fipscode"}),
	)
	s.AddTool(
		mcplib.NewTool("states_list",
			mcplib.WithDescription("List or search U.S. states. Optional: q. Returns the GenericSuccess."),
			mcplib.WithString("q", mcplib.Description("Search by state name or abbreviation")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/states/states", false, nil, []mcpParamBinding{{PublicName: "q", WireName: "q", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("text-language_detect",
			mcplib.WithDescription("Identifies the language of text with a confidence score. Supports 176+ languages with ISO 639-3 output. Requires at least 10 characters for reliable detection. Required: text. Optional: format (default: iso639-3), min_confidence. Returns the new GenericSuccess."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithNumber("min_confidence", mcplib.Description("Minimum confidence threshold")),
			mcplib.WithString("text", mcplib.Required(), mcplib.Description("Text")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/text-language/detect", false, nil, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "body"}, {PublicName: "min_confidence", WireName: "min_confidence", Location: "body"}, {PublicName: "text", WireName: "text", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("text-language_detect-batch",
			mcplib.WithDescription("Batch language detection for multiple texts. Required: texts. Returns the new GenericSuccess."),
			mcplib.WithString("texts", mcplib.Required(), mcplib.Description("Texts")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/text-language/detect-batch", false, nil, []mcpParamBinding{{PublicName: "texts", WireName: "texts", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("text-language_supported",
			mcplib.WithDescription("Returns all 176+ supported languages with ISO 639-1 and ISO 639-3 codes."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/text-language/supported", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("thesaurus_lookup",
			mcplib.WithDescription("Returns synonyms, antonyms, or both for a given word. Filter results by part of speech and limit the number of results. Required: word. Optional: type (default: synonyms), pos, limit (default: 20)."),
			mcplib.WithString("word", mcplib.Required(), mcplib.Description("The word to look up")),
			mcplib.WithString("type", mcplib.Description("Result type — synonyms, antonyms, or both")),
			mcplib.WithString("pos", mcplib.Description("Part of speech filter")),
			mcplib.WithNumber("limit", mcplib.Description("Maximum number of results (default 20)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/thesaurus", false, nil, []mcpParamBinding{{PublicName: "word", WireName: "word", Location: "query"}, {PublicName: "type", WireName: "type", Location: "query"}, {PublicName: "pos", WireName: "pos", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("unit-conversion_unit-categories",
			mcplib.WithDescription("List available measurement categories. Returns the GenericSuccess."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/unit-conversion/categories", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("unit-conversion_unit-convert-get",
			mcplib.WithDescription("Supports 100+ unit types across length, weight, temperature, volume, area, speed, digital storage, and time. Converts value from source unit to target unit. Required: from, to, value. Optional: precision (default: 4). Returns the GenericSuccess."),
			mcplib.WithString("from", mcplib.Required(), mcplib.Description("Source unit identifier (e.g. kg, lb, m, degC, km/h)")),
			mcplib.WithString("to", mcplib.Required(), mcplib.Description("Target unit identifier")),
			mcplib.WithNumber("value", mcplib.Required(), mcplib.Description("Value")),
			mcplib.WithNumber("precision", mcplib.Description("Decimal places in result (0-15)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/unit-conversion/convert", false, nil, []mcpParamBinding{{PublicName: "from", WireName: "from", Location: "query"}, {PublicName: "to", WireName: "to", Location: "query"}, {PublicName: "value", WireName: "value", Location: "query"}, {PublicName: "precision", WireName: "precision", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("unit-conversion_unit-convert-post",
			mcplib.WithDescription("Convert a value between units (POST). Required: from, to, value. Optional: precision. Returns the new GenericSuccess."),
			mcplib.WithString("from", mcplib.Required(), mcplib.Description("From")),
			mcplib.WithNumber("precision", mcplib.Description("Precision")),
			mcplib.WithString("to", mcplib.Required(), mcplib.Description("To")),
			mcplib.WithNumber("value", mcplib.Required(), mcplib.Description("Value")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/unit-conversion/convert", false, nil, []mcpParamBinding{{PublicName: "from", WireName: "from", Location: "body"}, {PublicName: "precision", WireName: "precision", Location: "body"}, {PublicName: "to", WireName: "to", Location: "body"}, {PublicName: "value", WireName: "value", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("unit-conversion_units-by-category",
			mcplib.WithDescription("List units available in a category. Required: category. Returns the GenericSuccess."),
			mcplib.WithString("category", mcplib.Required(), mcplib.Description("Measurement category (e.g. length, weight, temperature)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/unit-conversion/units/{category}", false, nil, []mcpParamBinding{{PublicName: "category", WireName: "category", Location: "path"}}, []string{"category"}),
	)
	s.AddTool(
		mcplib.NewTool("user-avatar_generate",
			mcplib.WithDescription("Creates avatar images using Canvas (PNG/WebP) or native SVG. Supports initials-based avatars, custom colors, external image integration, and uploaded icons. Optional: name, format (default: png), size (default: 128) (plus 3 more)."),
			mcplib.WithString("name", mcplib.Description("Display name to generate initials from")),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithNumber("size", mcplib.Description("Avatar size in pixels (16–512)")),
			mcplib.WithString("background", mcplib.Description("Background color hex without")),
			mcplib.WithString("color", mcplib.Description("Text/icon color hex without")),
			mcplib.WithBoolean("rounded", mcplib.Description("Output a circular avatar")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user-avatar", true, nil, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "query"}, {PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "size", WireName: "size", Location: "query"}, {PublicName: "background", WireName: "background", Location: "query"}, {PublicName: "color", WireName: "color", Location: "query"}, {PublicName: "rounded", WireName: "rounded", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("user-avatar_upload-icon",
			mcplib.WithDescription("Upload a custom icon for avatar generation. Required: file. Returns the new GenericSuccess."),
			mcplib.WithString("file", mcplib.Required(), mcplib.Description("Icon image file (PNG, SVG, or WebP, max 1MB)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/user-avatar/upload-icon", false, nil, []mcpParamBinding{{PublicName: "file", WireName: "file", Location: "body", Format: "binary", RequestContentType: "multipart/form-data"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("validate-ip_get",
			mcplib.WithDescription("Validates IPv4, IPv6, or CIDR notation and returns classification flags: private, reserved, loopback, multicast, link-local, bogon, and public. Supports comma-separated batch input (max 100). Required: ip."),
			mcplib.WithString("ip", mcplib.Required(), mcplib.Description("Single IP, CIDR notation, or comma-separated list (max 100)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/validate-ip/validate", false, nil, []mcpParamBinding{{PublicName: "ip", WireName: "ip", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("validate-ip_post",
			mcplib.WithDescription("Validate and classify IP addresses (POST). Required: ip. Returns the new GenericSuccess."),
			mcplib.WithString("ip", mcplib.Required(), mcplib.Description("Single IP string or array of IPs")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/validate-ip/validate", false, nil, []mcpParamBinding{{PublicName: "ip", WireName: "ip", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("vin-lookup_vin-decode",
			mcplib.WithDescription("Decodes 17-character Vehicle Identification Numbers using the official NHTSA vPIC database. Validates ISO 3779 check digit. Supports single VIN or batch array (max 50). Required: vin. Returns the new GenericSuccess."),
			mcplib.WithString("vin", mcplib.Required(), mcplib.Description("Single VIN string or array of VINs (max 50)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/vin-lookup/decode", false, nil, []mcpParamBinding{{PublicName: "vin", WireName: "vin", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("vin-lookup_vin-makes",
			mcplib.WithDescription("List all vehicle makes in the NHTSA database. Returns the GenericSuccess."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/vin-lookup/makes", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("vin-lookup_vin-sample-get",
			mcplib.WithDescription("Decode a single VIN via GET. Required: vin. Returns the GenericSuccess."),
			mcplib.WithString("vin", mcplib.Required(), mcplib.Description("17-character VIN")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/vin-lookup/sample/{vin}", false, nil, []mcpParamBinding{{PublicName: "vin", WireName: "vin", Location: "path"}}, []string{"vin"}),
	)
	s.AddTool(
		mcplib.NewTool("vin-lookup_vin-suggest",
			mcplib.WithDescription("Get VIN prefix suggestions for autocomplete. Required: prefix. Returns the GenericSuccess."),
			mcplib.WithString("prefix", mcplib.Required(), mcplib.Description("VIN prefix string (partial VIN)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/vin-lookup/suggest/{prefix}", false, nil, []mcpParamBinding{{PublicName: "prefix", WireName: "prefix", Location: "path"}}, []string{"prefix"}),
	)
	s.AddTool(
		mcplib.NewTool("web-screenshot_web_screenshot",
			mcplib.WithDescription("Renders a web page via Puppeteer headless browser and returns a screenshot. Supports viewport simulation, format selection, quality control, and crop. Required: url. Optional: width (default: 1280), height (default: 800), format (default: jpeg) (plus 2 more)."),
			mcplib.WithString("url", mcplib.Required(), mcplib.Description("Target URL including http/https scheme")),
			mcplib.WithNumber("width", mcplib.Description("Viewport width in pixels (100–3840, default 1280)")),
			mcplib.WithNumber("height", mcplib.Description("Viewport height in pixels (100–2160, default 800)")),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithNumber("quality", mcplib.Description("Image quality (10–100, default 100; ignored for PNG)")),
			mcplib.WithString("crop", mcplib.Description("Crop dimensions as WIDTHxHEIGHT (e.g. 800x600)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/web-screenshot", true, map[string]string{"Accept": "image/jpeg"}, []mcpParamBinding{{PublicName: "url", WireName: "url", Location: "query"}, {PublicName: "width", WireName: "width", Location: "query"}, {PublicName: "height", WireName: "height", Location: "query"}, {PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "quality", WireName: "quality", Location: "query"}, {PublicName: "crop", WireName: "crop", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("whois_lookup",
			mcplib.WithDescription("Returns registrar, registration date, expiration date, name servers, and raw WHOIS data. Supports single domain or batch array (max 50). Required: domain."),
			mcplib.WithString("domain", mcplib.Required(), mcplib.Description("Single domain string or array (max 50)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/whois/lookup", false, nil, []mcpParamBinding{{PublicName: "domain", WireName: "domain", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("working-days_batch",
			mcplib.WithDescription("Batch working day calculations. Required: requests. Returns the GenericSuccess."),
			mcplib.WithString("requests", mcplib.Required(), mcplib.Description("JSON-encoded array of calculation requests")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/working-days/calculate/batch", false, nil, []mcpParamBinding{{PublicName: "requests", WireName: "requests", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("working-days_calculate-get",
			mcplib.WithDescription("Calculate working days (GET). Required: start_date. Optional: end_date, days_offset, region (default: US). Returns the GenericSuccess."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Start date")),
			mcplib.WithString("end_date", mcplib.Description("End date")),
			mcplib.WithNumber("days_offset", mcplib.Description("Days offset")),
			mcplib.WithString("region", mcplib.Description("Region")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/working-days/calculate", false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "query"}, {PublicName: "end_date", WireName: "end_date", Location: "query"}, {PublicName: "days_offset", WireName: "days_offset", Location: "query"}, {PublicName: "region", WireName: "region", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("working-days_calculate-post",
			mcplib.WithDescription("For range calculations: provide start_date and end_date to get the number of working days between them. For offset calculations: provide start_date and days_offset to find the resulting business date. Supports US, DE, and IN regional holiday calendars. Required: start_date. Optional: days_offset, direction (default: forward), end_date (plus 1 more). Returns the new GenericSuccess."),
			mcplib.WithNumber("days_offset", mcplib.Description("Working days to add (positive) or subtract (negative)")),
			mcplib.WithString("direction", mcplib.Description("Direction")),
			mcplib.WithString("end_date", mcplib.Description("End date")),
			mcplib.WithString("region", mcplib.Description("Regional holiday calendar")),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Start date")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/working-days/calculate", false, nil, []mcpParamBinding{{PublicName: "days_offset", WireName: "days_offset", Location: "body"}, {PublicName: "direction", WireName: "direction", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}, {PublicName: "region", WireName: "region", Location: "body"}, {PublicName: "start_date", WireName: "start_date", Location: "body"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName         string
	WireName           string
	Location           string
	Format             string
	RequestContentType string
}

func mcpMultipartFieldValue(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	if data, err := json.Marshal(v); err == nil {
		return string(data)
	}
	return fmt.Sprintf("%v", v)
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c := clientFromContext(ctx)
		if c == nil {
			return mcplib.NewToolResultError("internal error: no API client in context — this MCP binary is missing its startup context hook (see internal/mcp/context.go)"), nil
		}
		var err error

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		multipartFields := make(map[string]string)
		multipartFileFields := make(map[string]string)
		multipart := false
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			if strings.EqualFold(binding.RequestContentType, "multipart/form-data") {
				multipart = true
			}
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
				if multipart {
					if strings.EqualFold(binding.Format, "binary") {
						multipartFileFields[binding.WireName] = fmt.Sprintf("%v", v)
					} else {
						multipartFields[binding.WireName] = mcpMultipartFieldValue(v)
					}
				}
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
				if multipart {
					multipartFields[k] = mcpMultipartFieldValue(v)
				}
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PostMultipartWithParamsAndHeaders(path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PostMultipartWithParams(path, params, multipartFields, multipartFileFields)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PutMultipartWithParamsAndHeaders(path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PutMultipartWithParams(path, params, multipartFields, multipartFileFields)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PatchMultipartWithParamsAndHeaders(path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PatchMultipartWithParams(path, params, multipartFields, multipartFileFields)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export DATPAQ_API_KEY=<your-key>" +
					"\n      See API docs: https://datpaq.com" +
					"\n      Run 'datpaq doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export DATPAQ_API_KEY=<your-key>" +
					"\n      See API docs: https://datpaq.com" +
					"\n      Run 'datpaq doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export DATPAQ_API_KEY=<your-key>" +
					"\n      See API docs: https://datpaq.com" +
					"\n      Run 'datpaq doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "datpaq", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "datpaq",
		"description": "Comprehensive multi-service API platform providing aviation, geolocation, financial, utilities, image processing,...",
		"archetype":   "crm",
		"tool_count":  88,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion datpaq binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "DATPAQ_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://datpaq.com",
		},
		"resources": []map[string]any{
			{
				"name":        "aircraft",
				"description": "FAA aircraft registry lookups by tail number, ICAO hex, or type code",
				"endpoints":   []string{"batch-lookup", "lookup-by-icao", "lookup-by-tail", "lookup-by-type"},
				"searchable":  true,
			},
			{
				"name":        "company-enrichment",
				"description": "Company data enrichment by name or domain",
				"endpoints":   []string{"company-enrich"},
				"searchable":  true,
			},
			{
				"name":        "convert-time",
				"description": "Timezone-aware datetime conversion",
				"endpoints":   []string{"convert_time"},
				"searchable":  true,
			},
			{
				"name":        "country-codes",
				"description": "ISO country code lookup and metadata",
				"endpoints":   []string{"country-by-iso", "country-export", "country-list", "country-search"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "current-time",
				"description": "Current time by IANA timezone identifier",
				"endpoints":   []string{"current_time"},
				"searchable":  true,
			},
			{
				"name":        "define",
				"description": "Manage define",
				"endpoints":   []string{"dictionary"},
				"searchable":  true,
			},
			{
				"name":        "dns",
				"description": "Manage dns",
				"endpoints":   []string{"lookup"},
				"searchable":  true,
			},
			{
				"name":        "domain-lookup",
				"description": "Domain availability and registration information",
				"endpoints":   []string{"get", "post"},
				"searchable":  true,
			},
			{
				"name":        "email-validation",
				"description": "Email address format and deliverability validation",
				"endpoints":   []string{"email-validate-batch", "email-validate-single"},
				"searchable":  true,
			},
			{
				"name":        "ev-charger",
				"description": "Electric vehicle charging station discovery and status",
				"endpoints":   []string{"ev-networks", "ev-station-by-id", "ev-station-status", "ev-stations-by-address", "ev-stations-by-coords"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "exchange-rates-and-currency",
				"description": "Manage exchange rates and currency",
				"endpoints":   []string{"exchange-rate-bulk", "exchange-rate-get"},
				"searchable":  true,
			},
			{
				"name":        "generate",
				"description": "Manage generate",
				"endpoints":   []string{"sample-data-post"},
				"searchable":  true,
			},
			{
				"name":        "generate-batch",
				"description": "Manage generate batch",
				"endpoints":   []string{"sample-data-post"},
			},
			{
				"name":        "helicopter",
				"description": "Helicopter registry lookups by registration, ICAO, or serial number",
				"endpoints":   []string{"lookup-by-icao", "lookup-by-registration", "lookup-by-serial", "manufacturers"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "image-processing",
				"description": "Image resize, compress, convert, crop, and pipeline operations",
				"endpoints":   []string{"image-compress", "image-convert", "image-crop", "image-metadata", "image-pipeline", "image-resize", "info"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "ip-geolocation",
				"description": "Geographic location data for IPv4 and IPv6 addresses",
				"endpoints":   []string{"batch", "get", "post"},
				"searchable":  true,
			},
			{
				"name":        "ip-intelligence",
				"description": "Threat intelligence and risk scoring for IP addresses",
				"endpoints":   []string{"batch", "batch-info", "get"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "mac-address",
				"description": "MAC address vendor and manufacturer resolution",
				"endpoints":   []string{"lookup"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "mx-lookup",
				"description": "Mail exchange record lookup with optional SMTP and SPF validation",
				"endpoints":   []string{"batch", "get", "post"},
				"searchable":  true,
			},
			{
				"name":        "precious-metals",
				"description": "Precious metal and cryptocurrency pricing data",
				"endpoints":   []string{"assets", "history", "prices"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "profanity",
				"description": "Content moderation and profanity detection",
				"endpoints":   []string{"analyze", "detect", "filter"},
				"searchable":  true,
			},
			{
				"name":        "public-holidays",
				"description": "Global public holiday data by country and year",
				"endpoints":   []string{"countries", "public_holidays"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "sample-data",
				"description": "Mock data generation for testing and development (Faker.js)",
				"endpoints":   []string{"batch-get", "batch-post", "generate-get"},
				"searchable":  true,
			},
			{
				"name":        "schemas",
				"description": "Manage schemas",
				"endpoints":   []string{"sample-data"},
				"syncable":    true,
			},
			{
				"name":        "secure-relay",
				"description": "Secure HMAC-verified HTTP request forwarding",
				"endpoints":   []string{"custom", "relay"},
				"searchable":  true,
			},
			{
				"name":        "spell-check",
				"description": "Multi-language spell checking with correction suggestions",
				"endpoints":   []string{"batch", "languages", "spell_check"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "states",
				"description": "U.S. state metadata by abbreviation or FIPS code",
				"endpoints":   []string{"by-abbr", "by-fips", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "text-language",
				"description": "Text language detection supporting 176+ languages",
				"endpoints":   []string{"detect", "detect-batch", "supported"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "thesaurus",
				"description": "Synonyms, antonyms, and related word lookup",
				"endpoints":   []string{"lookup"},
				"searchable":  true,
			},
			{
				"name":        "unit-conversion",
				"description": "Unit conversion across 100+ measurement types",
				"endpoints":   []string{"unit-categories", "unit-convert-get", "unit-convert-post", "units-by-category"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "user-avatar",
				"description": "Dynamic user avatar generation in PNG, WebP, or SVG",
				"endpoints":   []string{"generate", "upload-icon"},
				"searchable":  true,
			},
			{
				"name":        "validate-ip",
				"description": "IP address validation and classification (IPv4, IPv6, CIDR)",
				"endpoints":   []string{"get", "post"},
				"searchable":  true,
			},
			{
				"name":        "vin-lookup",
				"description": "Vehicle identification number decoding via NHTSA",
				"endpoints":   []string{"vin-decode", "vin-makes", "vin-sample-get", "vin-suggest"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "web-screenshot",
				"description": "Web page screenshot capture via headless browser",
				"endpoints":   []string{"web_screenshot"},
				"searchable":  true,
			},
			{
				"name":        "whois",
				"description": "Domain WHOIS registration data lookup",
				"endpoints":   []string{"lookup"},
				"searchable":  true,
			},
			{
				"name":        "working-days",
				"description": "Business day calculations with regional holiday support",
				"endpoints":   []string{"batch", "calculate-get", "calculate-post"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
