// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAircraftCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "aircraft",
		Short:  "FAA aircraft registry lookups by tail number, ICAO hex, or type code",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAircraftBatchLookupCmd(flags))
	cmd.AddCommand(newAircraftLookupByIcaoCmd(flags))
	cmd.AddCommand(newAircraftLookupByTailCmd(flags))
	cmd.AddCommand(newAircraftLookupByTypeCmd(flags))
	return cmd
}
