// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

func newAPICmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "api [interface]",
		Short:       "Browse all API endpoints by interface name",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Long: `Browse and call any API endpoint using the raw interface names.

The friendly top-level commands cover the most common operations.
This command provides access to ALL endpoints for power users and
agents that need full API coverage.

Run 'api' with no arguments to list all interfaces.
Run 'api <interface>' to see that interface's methods.`,
		Example: `  # List all available interfaces
  datpaq api

  # Show methods for a specific interface
  datpaq api <interface-name>`,
		RunE: func(cmd *cobra.Command, args []string) error {
			root := cmd.Root()

			// Build per-interface metadata by walking root.Commands() twice:
			// once for hidden-parent groups (the "raw" multi-endpoint
			// interfaces), once for promoted top-level commands (which carry
			// pp:endpoint annotations but aren't registered as Hidden).
			// The old implementation only counted hidden parents and missed
			// promoted interfaces like 'whois', 'current-time', and
			// 'web-screenshot' — which is why the active count was 9 instead
			// of 13.
			type ifaceMeta struct {
				short string
				cmd   *cobra.Command // hidden-parent for multi-endpoint, leaf for promoted
			}
			meta := map[string]*ifaceMeta{}
			for _, child := range root.Commands() {
				name := child.Name()
				if child.Hidden {
					// Multi-endpoint resource group — child IS the interface
					// parent; its methods are its cobra children.
					meta[name] = &ifaceMeta{short: child.Short, cmd: child}
					continue
				}
				if child.Annotations[annEndpoint] != "" {
					// Promoted top-level command — derive the interface name
					// from the annotation, since cobra Name() is the
					// command-line name (matches in this case).
					iface, _, _ := strings.Cut(child.Annotations[annEndpoint], ".")
					if iface == "" {
						iface = name
					}
					if _, exists := meta[iface]; !exists {
						meta[iface] = &ifaceMeta{short: child.Short, cmd: child}
					}
				}
			}

			if len(args) > 0 {
				target := strings.ToLower(args[0])
				m, ok := meta[target]
				if !ok {
					return fmt.Errorf("interface %q not found. Run 'datpaq api' to list all interfaces", args[0])
				}

				// Multi-endpoint: enumerate cobra children. Single-endpoint
				// (promoted): synthesize a one-row methods view from the
				// command itself so the UX stays uniform.
				type methodRow struct {
					Name  string `json:"name"`
					Short string `json:"short"`
				}
				var rows []methodRow
				if m.cmd.Hidden && m.cmd.HasSubCommands() {
					for _, mc := range m.cmd.Commands() {
						rows = append(rows, methodRow{Name: mc.Name(), Short: mc.Short})
					}
				} else {
					// Promoted: the interface and the method are the same
					// command. Use the cobra Use name (just the verb) for
					// the row label.
					rows = append(rows, methodRow{Name: m.cmd.Name(), Short: m.cmd.Short})
				}

				if flags.asJSON {
					methodList := make([]map[string]any, 0, len(rows))
					for _, r := range rows {
						methodList = append(methodList, map[string]any{"name": r.Name, "short": r.Short})
					}
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"interface": target,
						"short":     m.short,
						"methods":   methodList,
					}, flags)
				}
				// Single-endpoint promoted interfaces (e.g. whois, current-time)
				// have one row whose name happens to equal the interface name.
				// "whois whois" reads as a typo; collapse it to "whois (single
				// endpoint)" and adjust the help-hint to match the actual
				// invocation shape ('datpaq whois --help', no method slot).
				singleEndpoint := len(rows) == 1 && rows[0].Name == target

				fmt.Fprintf(cmd.OutOrStdout(), "%s — %s\n\nMethods:\n", target, m.short)
				for _, r := range rows {
					label := target + " " + r.Name
					if singleEndpoint {
						label = target + " (single endpoint)"
					}
					fmt.Fprintf(cmd.OutOrStdout(), "  %-50s %s\n", label, r.Short)
				}
				if singleEndpoint {
					fmt.Fprintf(cmd.OutOrStdout(), "\nUse 'datpaq %s --help' for details.\n", target)
				} else {
					fmt.Fprintf(cmd.OutOrStdout(), "\nUse 'datpaq %s <method> --help' for details.\n", target)
				}
				return nil
			}

			// No args: list interfaces.
			type ifaceEntry struct {
				Name  string `json:"name"`
				Short string `json:"short"`
			}
			var ifaces []ifaceEntry
			for name, m := range meta {
				if !IsActiveInterface(name) {
					continue
				}
				ifaces = append(ifaces, ifaceEntry{Name: name, Short: m.short})
			}
			sort.Slice(ifaces, func(i, j int) bool { return ifaces[i].Name < ifaces[j].Name })

			if flags.asJSON {
				out := map[string]any{"interfaces": ifaces}
				if len(ifaces) == 0 {
					out["interfaces"] = []ifaceEntry{}
					out["note"] = "No active API interfaces found."
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if len(ifaces) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "No active API interfaces found.")
				return nil
			}

			// Label uses "N active" when a curated active-set is in effect,
			// "N interfaces" otherwise. Avoids the "N of M" form since N is
			// the only number that matters to the reader.
			if activeAPICount() > 0 {
				fmt.Fprintf(cmd.OutOrStdout(), "Available API interfaces (%d active):\n\n", len(ifaces))
			} else {
				fmt.Fprintf(cmd.OutOrStdout(), "Available API interfaces (%d):\n\n", len(ifaces))
			}
			for _, e := range ifaces {
				fmt.Fprintf(cmd.OutOrStdout(), "  %-45s %s\n", e.Name, e.Short)
			}
			fmt.Fprintln(cmd.OutOrStdout(), "\nUse 'datpaq api <interface>' to see methods.")
			fmt.Fprintln(cmd.OutOrStdout(), "Use 'datpaq exec list' to see endpoints callable via 'datpaq exec'.")
			return nil
		},
	}

	return cmd
}
