// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Hand-authored: browser-based Clerk SSO login flow. Not generated by
// printing-press — survives `--force` regenerations via AST-based merge.
//
// Wire contract is documented in docs/cli-auth-spec.md (repo-relative).

package cli

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"time"

	"github.com/datpaq/mcp/internal/cliutil"
	"github.com/datpaq/mcp/internal/config"
	"github.com/spf13/cobra"
)

// Defaults are package-level so tests / verify mode can override without
// reaching into the cobra command builder.
var (
	authLoginAuthURL      = "https://datpaq.com/cli/auth"
	authLoginExchangeURL  = "https://datpaq.com/api/v1/cli/auth/exchange"
	authLoginDefaultWait  = 5 * time.Minute
	authLoginCallbackPath = "/callback"
)

// exchangeResponse mirrors the body documented in cli-auth-spec.md §"Endpoint 2".
type exchangeResponse struct {
	APIKey    string `json:"api_key"`
	ExpiresAt string `json:"expires_at,omitempty"`
	User      struct {
		ID    string `json:"id"`
		Email string `json:"email"`
	} `json:"user"`
}

func newAuthLoginCmd(flags *rootFlags) *cobra.Command {
	var (
		noBrowser   bool
		timeout     time.Duration
		authURL     string
		exchangeURL string
	)
	cmd := &cobra.Command{
		Use:   "login",
		Short: "Sign in via the datpaq.com browser flow (Clerk SSO)",
		Long: "Opens your browser to datpaq.com for Clerk-backed sign-in " +
			"(Google, GitHub, or email/password), then captures your API key " +
			"via a one-shot loopback listener and saves it to the local config.\n\n" +
			"Use `datpaq auth set-token <key>` instead when you can't reach a " +
			"browser (SSH, CI, headless).",
		Example: "  datpaq auth login\n  datpaq auth login --no-browser",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Short-circuit in the printing-press verify sandbox so dogfood
			// runs don't try to open browsers or bind sockets.
			if cliutil.IsVerifyEnv() {
				fmt.Fprintln(cmd.OutOrStdout(), "would open browser-based login flow")
				return nil
			}

			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Resolve effective URLs: flag overrides win, otherwise use the
			// production defaults. The flags are primarily for local dev
			// against a localhost website / staging environments.
			effectiveAuthURL := authURL
			if effectiveAuthURL == "" {
				effectiveAuthURL = authLoginAuthURL
			}
			effectiveExchangeURL := exchangeURL
			if effectiveExchangeURL == "" {
				effectiveExchangeURL = authLoginExchangeURL
			}

			state, err := randomNonce(32)
			if err != nil {
				return fmt.Errorf("generating state nonce: %w", err)
			}

			// Bind a loopback listener on an ephemeral port. ":0" lets the
			// kernel pick — avoids fighting other CLIs over a fixed port.
			ln, err := net.Listen("tcp", "127.0.0.1:0")
			if err != nil {
				return fmt.Errorf("binding loopback listener: %w", err)
			}
			port := ln.Addr().(*net.TCPAddr).Port

			// Buffered so the handler can send-and-return even if RunE has
			// already moved on (e.g. timeout fired first).
			resultCh := make(chan callbackResult, 1)
			srv := &http.Server{
				Handler:           buildCallbackMux(state, resultCh),
				ReadHeaderTimeout: 5 * time.Second,
			}
			go func() { _ = srv.Serve(ln) }()
			defer func() {
				shutdownCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
				defer cancel()
				_ = srv.Shutdown(shutdownCtx)
			}()

			browserURL := buildAuthURL(effectiveAuthURL, port, state)
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "Opening browser to sign in…")
			fmt.Fprintln(w, "  ", browserURL)
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "Waiting for callback. Press Ctrl+C to cancel.")

			if !noBrowser {
				if err := openSetupURL(browserURL); err != nil {
					fmt.Fprintf(cmd.ErrOrStderr(),
						"could not open browser automatically (%v); open the URL above manually.\n", err)
				}
			}

			deadline := time.NewTimer(timeout)
			defer deadline.Stop()

			select {
			case <-deadline.C:
				return fmt.Errorf("timed out after %s waiting for browser callback", timeout)
			case res := <-resultCh:
				if res.err != nil {
					return res.err
				}
				exch, err := exchangeCode(cmd.Context(), effectiveExchangeURL, res.code, state)
				if err != nil {
					return fmt.Errorf("exchanging code for API key: %w", err)
				}
				if exch.APIKey == "" {
					return fmt.Errorf("exchange response missing api_key")
				}
				// Clear any stale auth_header so SaveCredential's slot is the
				// one AuthHeader() reads. Mirrors the pattern in set-token.
				cfg.AuthHeaderVal = ""
				if err := cfg.SaveCredential(exch.APIKey); err != nil {
					return configErr(fmt.Errorf("saving API key: %w", err))
				}

				if flags.asJSON {
					return printJSONFiltered(w, map[string]any{
						"logged_in":   true,
						"user_email":  exch.User.Email,
						"user_id":     exch.User.ID,
						"config_path": cfg.Path,
					}, flags)
				}
				fmt.Fprintf(w, "\n✓ Logged in as %s\n", exch.User.Email)
				fmt.Fprintf(w, "  API key saved to %s\n", cfg.Path)
				return nil
			}
		},
	}
	cmd.Flags().BoolVar(&noBrowser, "no-browser", false,
		"Print the auth URL but do not auto-open the browser")
	cmd.Flags().DurationVar(&timeout, "timeout", authLoginDefaultWait,
		"How long to wait for the browser callback")
	cmd.Flags().StringVar(&authURL, "auth-url", "",
		"Override the browser sign-in URL (advanced; for local dev against a non-production website)")
	cmd.Flags().StringVar(&exchangeURL, "exchange-url", "",
		"Override the code-exchange endpoint URL (advanced; for local dev against a non-production website)")
	return cmd
}

// callbackResult is what the loopback handler sends back to the command
// goroutine. Either code is set (success) or err is set (validation failure).
type callbackResult struct {
	code string
	err  error
}

func buildCallbackMux(expectedState string, ch chan<- callbackResult) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc(authLoginCallbackPath, func(w http.ResponseWriter, r *http.Request) {
		q := r.URL.Query()
		gotState := q.Get("state")
		code := q.Get("code")

		// CSRF defense: the state we generated must come back verbatim.
		// Without this check, a malicious page on any origin could forge a
		// callback while the listener is up and inject an attacker-controlled
		// code.
		if gotState != expectedState {
			http.Error(w, "state mismatch", http.StatusBadRequest)
			select {
			case ch <- callbackResult{err: fmt.Errorf("callback state mismatch (possible CSRF)")}:
			default:
			}
			return
		}
		if code == "" {
			msg := q.Get("error_description")
			if msg == "" {
				msg = q.Get("error")
			}
			if msg == "" {
				msg = "callback missing 'code' query parameter"
			}
			http.Error(w, msg, http.StatusBadRequest)
			select {
			case ch <- callbackResult{err: fmt.Errorf("login failed: %s", msg)}:
			default:
			}
			return
		}

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(callbackSuccessHTML))
		select {
		case ch <- callbackResult{code: code}:
		default:
		}
	})
	return mux
}

func buildAuthURL(baseURL string, port int, state string) string {
	u, err := url.Parse(baseURL)
	if err != nil {
		// Parse failures are only reachable via a malformed --auth-url
		// override; fall back to a string-concatenated URL so the user at
		// least sees what the CLI tried.
		return fmt.Sprintf("%s?port=%d&state=%s", baseURL, port, state)
	}
	q := u.Query()
	q.Set("port", fmt.Sprintf("%d", port))
	q.Set("state", state)
	u.RawQuery = q.Encode()
	return u.String()
}

func exchangeCode(ctx context.Context, exchangeURL, code, state string) (*exchangeResponse, error) {
	body, err := json.Marshal(map[string]string{"code": code, "state": state})
	if err != nil {
		return nil, err
	}
	reqCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(reqCtx, http.MethodPost, exchangeURL, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		var errBody struct {
			Error   string `json:"error"`
			Message string `json:"message"`
		}
		_ = json.NewDecoder(resp.Body).Decode(&errBody)
		switch {
		case errBody.Message != "":
			return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, errBody.Message)
		case errBody.Error != "":
			return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, errBody.Error)
		default:
			return nil, fmt.Errorf("HTTP %d from exchange endpoint", resp.StatusCode)
		}
	}

	var out exchangeResponse
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, fmt.Errorf("decoding exchange response: %w", err)
	}
	return &out, nil
}

func randomNonce(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

const callbackSuccessHTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Datpaq CLI — Signed in</title>
<style>
  body {
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    background: #0b0118;
    color: #e9d5ff;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
    margin: 0;
  }
  .card {
    text-align: center;
    padding: 2.5rem 3rem;
    border: 1px solid #6b21a8;
    border-radius: 12px;
    background: linear-gradient(180deg, rgba(157,78,192,0.08), rgba(107,33,168,0.02));
    box-shadow: 0 0 60px rgba(157,78,192,0.25);
  }
  h1 { margin: 0 0 .5rem; font-size: 1.5rem; color: #d987ea; }
  p { margin: .25rem 0; color: #b8a3ff; }
  .small { color: #64748b; font-size: .85rem; margin-top: 1.25rem; }
</style>
</head>
<body>
  <div class="card">
    <h1>✓ Signed in</h1>
    <p>You can close this window and return to your terminal.</p>
    <p class="small">datpaq CLI · datpaq.com</p>
  </div>
</body>
</html>
`
