// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCountryCodesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "country-codes",
		Short:  "ISO country code lookup and metadata",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCountryCodesCountryByIsoCmd(flags))
	cmd.AddCommand(newCountryCodesCountryExportCmd(flags))
	cmd.AddCommand(newCountryCodesCountryListCmd(flags))
	cmd.AddCommand(newCountryCodesCountrySearchCmd(flags))
	return cmd
}
