// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEmailValidationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "email-validation",
		Short:  "Email address format and deliverability validation",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEmailValidationEmailValidateBatchCmd(flags))
	cmd.AddCommand(newEmailValidationEmailValidateSingleCmd(flags))
	return cmd
}
