// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEvChargerEvStationsByCoordsCmd(flags *rootFlags) *cobra.Command {
	var flagLat float64
	var flagLon float64
	var flagRadius float64

	cmd := &cobra.Command{
		Use:         "ev-stations-by-coords",
		Short:       "Find EV charging stations near coordinates",
		Example:     "  datpaq ev-charger ev-stations-by-coords --lat 42 --lon 42",
		Annotations: map[string]string{"pp:endpoint": "ev-charger.ev-stations-by-coords", "pp:method": "GET", "pp:path": "/ev-charger/stations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("lat") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "lat")
			}
			if !cmd.Flags().Changed("lon") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "lon")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/ev-charger/stations"
			params := map[string]string{}
			if flagLat != 0.0 {
				params["lat"] = fmt.Sprintf("%v", flagLat)
			}
			if flagLon != 0.0 {
				params["lon"] = fmt.Sprintf("%v", flagLon)
			}
			if flagRadius != 0.0 {
				params["radius"] = fmt.Sprintf("%v", flagRadius)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "ev-charger", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&flagLat, "lat", 0.0, "Latitude (-90 to 90)")
	cmd.Flags().Float64Var(&flagLon, "lon", 0.0, "Longitude (-180 to 180)")
	cmd.Flags().Float64Var(&flagRadius, "radius", 5.000000, "Search radius in miles (max 100, default 5)")

	return cmd
}
