// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEvChargerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "ev-charger",
		Short:  "Electric vehicle charging station discovery and status",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEvChargerEvNetworksCmd(flags))
	cmd.AddCommand(newEvChargerEvStationByIdCmd(flags))
	cmd.AddCommand(newEvChargerEvStationStatusCmd(flags))
	cmd.AddCommand(newEvChargerEvStationsByAddressCmd(flags))
	cmd.AddCommand(newEvChargerEvStationsByCoordsCmd(flags))
	return cmd
}
