// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newExchangeRatesAndCurrencyExchangeRateGetCmd(flags *rootFlags) *cobra.Command {
	var flagFrom string
	var flagTo string
	var flagAmount float64

	cmd := &cobra.Command{
		Use:         "exchange-rate-get",
		Aliases:     []string{"list"},
		Short:       "Returns the current exchange rate between two currencies. Provide an amount to perform conversion. Supports fiat...",
		Example:     "  datpaq exchange-rates-and-currency exchange-rate-get --from example-value --to example-value",
		Annotations: map[string]string{"pp:endpoint": "exchange-rates-and-currency.exchange-rate-get", "pp:method": "GET", "pp:path": "/exchange-rates-and-currency/api/exchange", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("from") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "from")
			}
			if !cmd.Flags().Changed("to") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "to")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/exchange-rates-and-currency/api/exchange"
			params := map[string]string{}
			if flagFrom != "" {
				params["from"] = fmt.Sprintf("%v", flagFrom)
			}
			if flagTo != "" {
				params["to"] = fmt.Sprintf("%v", flagTo)
			}
			if flagAmount != 0.0 {
				params["amount"] = fmt.Sprintf("%v", flagAmount)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "exchange-rates-and-currency", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagFrom, "from", "", "Source currency code (e.g. USD) or crypto symbol (e.g. BTC)")
	cmd.Flags().StringVar(&flagTo, "to", "", "Target currency code")
	cmd.Flags().Float64Var(&flagAmount, "amount", 0.0, "Amount to convert. Omit to retrieve rate only.")

	return cmd
}
