// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newExchangeRatesAndCurrencyCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "exchange-rates-and-currency",
		Short:  "Manage exchange rates and currency",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newExchangeRatesAndCurrencyExchangeRateBulkCmd(flags))
	cmd.AddCommand(newExchangeRatesAndCurrencyExchangeRateGetCmd(flags))
	return cmd
}
