// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newHelicopterCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "helicopter",
		Short:  "Helicopter registry lookups by registration, ICAO, or serial number",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newHelicopterLookupByIcaoCmd(flags))
	cmd.AddCommand(newHelicopterLookupByRegistrationCmd(flags))
	cmd.AddCommand(newHelicopterLookupBySerialCmd(flags))
	cmd.AddCommand(newHelicopterManufacturersCmd(flags))
	return cmd
}
