// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newImageProcessingImageResizeCmd(flags *rootFlags) *cobra.Command {
	var bodyFit string
	var bodyHeight int
	var bodyImageUrl string
	var bodyWidth int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "image-resize",
		Short:       "Resize an image to specified dimensions",
		Example:     "  datpaq image-processing image-resize --image-url https://example.com/resource",
		Annotations: map[string]string{"pp:endpoint": "image-processing.image-resize", "pp:method": "POST", "pp:path": "/image-processing/resize"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("image-url") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "image-url")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/image-processing/resize"
			headerOverrides := map[string]string{
				"Accept":                           "image/jpeg",
				"X-Printing-Press-Binary-Response": "true",
			}
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyFit != "" {
					body["fit"] = bodyFit
				}
				if bodyHeight != 0 {
					body["height"] = bodyHeight
				}
				if bodyImageUrl != "" {
					body["image_url"] = bodyImageUrl
				}
				if bodyWidth != 0 {
					body["width"] = bodyWidth
				}
			}
			data, statusCode, err := c.PostWithParamsAndHeaders(path, params, body, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = statusCode
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}
	cmd.Flags().StringVar(&bodyFit, "fit", "cover", "Fit")
	cmd.Flags().IntVar(&bodyHeight, "height", 0, "Height")
	cmd.Flags().StringVar(&bodyImageUrl, "image-url", "", "Image url")
	cmd.Flags().IntVar(&bodyWidth, "width", 0, "Width")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
