// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newImageProcessingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "image-processing",
		Short:  "Image resize, compress, convert, crop, and pipeline operations",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newImageProcessingImageCompressCmd(flags))
	cmd.AddCommand(newImageProcessingImageConvertCmd(flags))
	cmd.AddCommand(newImageProcessingImageCropCmd(flags))
	cmd.AddCommand(newImageProcessingImageMetadataCmd(flags))
	cmd.AddCommand(newImageProcessingImagePipelineCmd(flags))
	cmd.AddCommand(newImageProcessingImageResizeCmd(flags))
	cmd.AddCommand(newImageProcessingInfoCmd(flags))
	return cmd
}
