// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIpGeolocationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "ip-geolocation",
		Short:  "Geographic location data for IPv4 and IPv6 addresses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIpGeolocationBatchCmd(flags))
	cmd.AddCommand(newIpGeolocationGetCmd(flags))
	cmd.AddCommand(newIpGeolocationPostCmd(flags))
	return cmd
}
