// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIpIntelligenceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "ip-intelligence",
		Short:  "Threat intelligence and risk scoring for IP addresses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIpIntelligenceBatchCmd(flags))
	cmd.AddCommand(newIpIntelligenceBatchInfoCmd(flags))
	cmd.AddCommand(newIpIntelligenceGetCmd(flags))
	return cmd
}
