// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMxLookupCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "mx-lookup",
		Short:  "Mail exchange record lookup with optional SMTP and SPF validation",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMxLookupBatchCmd(flags))
	cmd.AddCommand(newMxLookupGetCmd(flags))
	cmd.AddCommand(newMxLookupPostCmd(flags))
	return cmd
}
