// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPreciousMetalsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "precious-metals",
		Short:  "Precious metal and cryptocurrency pricing data",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPreciousMetalsAssetsCmd(flags))
	cmd.AddCommand(newPreciousMetalsHistoryCmd(flags))
	cmd.AddCommand(newPreciousMetalsPricesCmd(flags))
	return cmd
}
