// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProfanityCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "profanity",
		Short:  "Content moderation and profanity detection",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProfanityAnalyzeCmd(flags))
	cmd.AddCommand(newProfanityDetectCmd(flags))
	cmd.AddCommand(newProfanityFilterCmd(flags))
	return cmd
}
