// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newWebScreenshotPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagUrl string
	var flagWidth int
	var flagHeight int
	var flagFormat string
	var flagQuality int
	var flagCrop string

	cmd := &cobra.Command{
		Use:         "web-screenshot",
		Short:       "Renders a web page via Puppeteer headless browser and returns a screenshot. Supports viewport simulation, format...",
		Long:        "Shortcut for 'web-screenshot web_screenshot'. Renders a web page via Puppeteer headless browser and returns a screenshot. Supports viewport simulation, format...",
		Example:     "  datpaq web-screenshot --url https://example.com/resource",
		Annotations: map[string]string{"pp:endpoint": "web-screenshot.web_screenshot", "pp:method": "GET", "pp:path": "/web-screenshot", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("url") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "url")
			}
			if cmd.Flags().Changed("format") {
				allowedFormat := []string{"jpeg", "png", "webp"}
				validFormat := false
				for _, v := range allowedFormat {
					if flagFormat == v {
						validFormat = true
						break
					}
				}
				if !validFormat {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "format", flagFormat, allowedFormat)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/web-screenshot"
			headerOverrides := map[string]string{
				"Accept":                           "image/jpeg",
				"X-Printing-Press-Binary-Response": "true",
			}
			params := map[string]string{}
			if flagUrl != "" {
				params["url"] = fmt.Sprintf("%v", flagUrl)
			}
			if flagWidth != 0 {
				params["width"] = fmt.Sprintf("%v", flagWidth)
			}
			if flagHeight != 0 {
				params["height"] = fmt.Sprintf("%v", flagHeight)
			}
			if flagFormat != "" {
				params["format"] = fmt.Sprintf("%v", flagFormat)
			}
			if flagQuality != 0 {
				params["quality"] = fmt.Sprintf("%v", flagQuality)
			}
			if flagCrop != "" {
				params["crop"] = fmt.Sprintf("%v", flagCrop)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "web-screenshot", false, path, params, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}
	cmd.Flags().StringVar(&flagUrl, "url", "", "Target URL including http/https scheme")
	cmd.Flags().IntVar(&flagWidth, "width", 1280, "Viewport width in pixels (100–3840, default 1280)")
	cmd.Flags().IntVar(&flagHeight, "height", 800, "Viewport height in pixels (100–2160, default 800)")
	cmd.Flags().StringVar(&flagFormat, "format", "jpeg", "Format (one of: jpeg, png, webp)")
	cmd.Flags().IntVar(&flagQuality, "quality", 100, "Image quality (10–100, default 100; ignored for PNG)")
	cmd.Flags().StringVar(&flagCrop, "crop", "", "Crop dimensions as WIDTHxHEIGHT (e.g. 800x600)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
