// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPublicHolidaysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "public-holidays",
		Short:  "Global public holiday data by country and year",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPublicHolidaysCountriesCmd(flags))
	cmd.AddCommand(newPublicHolidaysPublicHolidaysCmd(flags))
	return cmd
}
