// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSampleDataCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "sample-data",
		Short:  "Mock data generation for testing and development (Faker.js)",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSampleDataBatchGetCmd(flags))
	cmd.AddCommand(newSampleDataBatchPostCmd(flags))
	cmd.AddCommand(newSampleDataGenerateGetCmd(flags))
	return cmd
}
