// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSampleDataGenerateGetCmd(flags *rootFlags) *cobra.Command {
	var flagType string
	var flagCount int
	var flagFields string
	var flagFormat string

	cmd := &cobra.Command{
		Use:         "generate-get",
		Short:       "GET-compatible sample data generation endpoint for scripts and browser testing.",
		Example:     "  datpaq sample-data generate-get --type example-value",
		Annotations: map[string]string{"pp:endpoint": "sample-data.generate-get", "pp:method": "GET", "pp:path": "/sample-data", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("type") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "type")
			}
			if cmd.Flags().Changed("format") {
				allowedFormat := []string{"json", "csv"}
				validFormat := false
				for _, v := range allowedFormat {
					if flagFormat == v {
						validFormat = true
						break
					}
				}
				if !validFormat {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "format", flagFormat, allowedFormat)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sample-data"
			params := map[string]string{}
			if flagType != "" {
				params["type"] = fmt.Sprintf("%v", flagType)
			}
			if flagCount != 0 {
				params["count"] = fmt.Sprintf("%v", flagCount)
			}
			if flagFields != "" {
				params["fields"] = fmt.Sprintf("%v", flagFields)
			}
			if flagFormat != "" {
				params["format"] = fmt.Sprintf("%v", flagFormat)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "sample-data", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagType, "type", "", "Schema type to generate, such as user, company, product, or transaction.")
	cmd.Flags().IntVar(&flagCount, "count", 1, "Number of records to generate.")
	cmd.Flags().StringVar(&flagFields, "fields", "", "Comma-separated list of fields to include.")
	cmd.Flags().StringVar(&flagFormat, "format", "json", "Response format. (one of: json, csv)")

	return cmd
}
