// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSecureRelayCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "secure-relay",
		Short:  "Secure HMAC-verified HTTP request forwarding",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSecureRelayCustomCmd(flags))
	cmd.AddCommand(newSecureRelayRelayCmd(flags))
	return cmd
}
