// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSpellCheckCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "spell-check",
		Short:  "Multi-language spell checking with correction suggestions",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSpellCheckBatchCmd(flags))
	cmd.AddCommand(newSpellCheckLanguagesCmd(flags))
	cmd.AddCommand(newSpellCheckSpellCheckCmd(flags))
	return cmd
}
