// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "states",
		Short:  "U.S. state metadata by abbreviation or FIPS code",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStatesByAbbrCmd(flags))
	cmd.AddCommand(newStatesByFipsCmd(flags))
	cmd.AddCommand(newStatesListCmd(flags))
	return cmd
}
