// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTextLanguageCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "text-language",
		Short:  "Text language detection supporting 176+ languages",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTextLanguageDetectCmd(flags))
	cmd.AddCommand(newTextLanguageDetectBatchCmd(flags))
	cmd.AddCommand(newTextLanguageSupportedCmd(flags))
	return cmd
}
