// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUnitConversionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "unit-conversion",
		Short:  "Unit conversion across 100+ measurement types",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUnitConversionUnitCategoriesCmd(flags))
	cmd.AddCommand(newUnitConversionUnitConvertGetCmd(flags))
	cmd.AddCommand(newUnitConversionUnitConvertPostCmd(flags))
	cmd.AddCommand(newUnitConversionUnitsByCategoryCmd(flags))
	return cmd
}
