// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUserAvatarCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "user-avatar",
		Short:  "Dynamic user avatar generation in PNG, WebP, or SVG",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUserAvatarGenerateCmd(flags))
	cmd.AddCommand(newUserAvatarUploadIconCmd(flags))
	return cmd
}
