// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUserAvatarGenerateCmd(flags *rootFlags) *cobra.Command {
	var flagName string
	var flagFormat string
	var flagSize int
	var flagBackground string
	var flagColor string
	var flagRounded bool

	cmd := &cobra.Command{
		Use:         "generate",
		Aliases:     []string{"list"},
		Short:       "Creates avatar images using Canvas (PNG/WebP) or native SVG. Supports initials-based avatars, custom colors,...",
		Example:     "  datpaq user-avatar generate",
		Annotations: map[string]string{"pp:endpoint": "user-avatar.generate", "pp:method": "GET", "pp:path": "/user-avatar", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("format") {
				allowedFormat := []string{"png", "webp", "svg"}
				validFormat := false
				for _, v := range allowedFormat {
					if flagFormat == v {
						validFormat = true
						break
					}
				}
				if !validFormat {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "format", flagFormat, allowedFormat)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/user-avatar"
			headerOverrides := map[string]string{
				"X-Printing-Press-Binary-Response": "true",
			}
			params := map[string]string{}
			if flagName != "" {
				params["name"] = fmt.Sprintf("%v", flagName)
			}
			if flagFormat != "" {
				params["format"] = fmt.Sprintf("%v", flagFormat)
			}
			if flagSize != 0 {
				params["size"] = fmt.Sprintf("%v", flagSize)
			}
			if flagBackground != "" {
				params["background"] = fmt.Sprintf("%v", flagBackground)
			}
			if flagColor != "" {
				params["color"] = fmt.Sprintf("%v", flagColor)
			}
			if flagRounded != false {
				params["rounded"] = fmt.Sprintf("%v", flagRounded)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "user-avatar", false, path, params, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}
	cmd.Flags().StringVar(&flagName, "name", "", "Display name to generate initials from")
	cmd.Flags().StringVar(&flagFormat, "format", "png", "Format (one of: png, webp, svg)")
	cmd.Flags().IntVar(&flagSize, "size", 128, "Avatar size in pixels (16–512)")
	cmd.Flags().StringVar(&flagBackground, "background", "", "Background color hex without")
	cmd.Flags().StringVar(&flagColor, "color", "", "Text/icon color hex without")
	cmd.Flags().BoolVar(&flagRounded, "rounded", false, "Output a circular avatar")

	return cmd
}
