// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newValidateIpCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "validate-ip",
		Short:  "IP address validation and classification (IPv4, IPv6, CIDR)",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newValidateIpGetCmd(flags))
	cmd.AddCommand(newValidateIpPostCmd(flags))
	return cmd
}
