// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newVinLookupCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "vin-lookup",
		Short:  "Vehicle identification number decoding via NHTSA",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newVinLookupVinDecodeCmd(flags))
	cmd.AddCommand(newVinLookupVinMakesCmd(flags))
	cmd.AddCommand(newVinLookupVinSampleGetCmd(flags))
	cmd.AddCommand(newVinLookupVinSuggestCmd(flags))
	return cmd
}
