// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "aircraft batch-lookup", Description: "Batch aircraft lookups by tail number", Group: "aircraft"},
	{Command: "aircraft lookup-by-icao", Description: "Look up aircraft by ICAO hex code", Group: "aircraft"},
	{Command: "aircraft lookup-by-tail", Description: "Returns aircraft ownership, manufacturer, model, type, and year from the FAA registry using an N-number (tail number).", Group: "aircraft"},
	{Command: "aircraft lookup-by-type", Description: "Look up aircraft type specifications", Group: "aircraft"},
	{Command: "company-enrichment company-enrich", Description: "Returns structured company data including industry, size, social profiles, and contact information. Provide company_name, domain, or both.", Group: "company-enrichment"},
	{Command: "convert-time convert_time", Description: "Converts a datetime value from a source timezone to a target timezone. Accepts ISO 8601 strings, Unix epoch timestamps, or omit sourceTime to convert the current time.", Group: "convert-time"},
	{Command: "country-codes country-by-iso", Description: "Get a country by ISO 2 or ISO 3 code", Group: "country-codes"},
	{Command: "country-codes country-export", Description: "Export country data in bulk", Group: "country-codes"},
	{Command: "country-codes country-list", Description: "List all countries with ISO codes and metadata", Group: "country-codes"},
	{Command: "country-codes country-search", Description: "Search countries by full or partial name", Group: "country-codes"},
	{Command: "current-time current_time", Description: "Returns the current date/time with UTC offset and DST status for a given timezone.", Group: "current-time"},
	{Command: "define dictionary", Description: "Returns definitions, part of speech, pronunciation, and etymology for the given word.", Group: "define"},
	{Command: "dns lookup", Description: "Supports record types A, AAAA, MX, CNAME, TXT, NS, SOA, and ALL.", Group: "dns"},
	{Command: "domain-lookup get", Description: "Check domain availability and registration info", Group: "domain-lookup"},
	{Command: "domain-lookup post", Description: "Check domain availability (POST)", Group: "domain-lookup"},
	{Command: "email-validation email-validate-batch", Description: "Validate multiple email addresses", Group: "email-validation"},
	{Command: "email-validation email-validate-single", Description: "Checks email format, domain MX records, and optional deliverability. Detects disposable/temporary address providers.", Group: "email-validation"},
	{Command: "ev-charger ev-networks", Description: "List all supported charging networks", Group: "ev-charger"},
	{Command: "ev-charger ev-station-by-id", Description: "Get specific charging station by ID", Group: "ev-charger"},
	{Command: "ev-charger ev-station-status", Description: "Get real-time station status", Group: "ev-charger"},
	{Command: "ev-charger ev-stations-by-address", Description: "Search EV charging stations by address", Group: "ev-charger"},
	{Command: "ev-charger ev-stations-by-coords", Description: "Find EV charging stations near coordinates", Group: "ev-charger"},
	{Command: "exchange-rates-and-currency exchange-rate-bulk", Description: "Batch currency conversions", Group: "exchange-rates-and-currency"},
	{Command: "exchange-rates-and-currency exchange-rate-get", Description: "Returns the current exchange rate between two currencies. Provide an amount to perform conversion. Supports fiat (ISO 4217) and crypto (BTC, ETH).", Group: "exchange-rates-and-currency"},
	{Command: "generate sample-data-post", Description: "Generate realistic mock data using a JSON request body. Recommended for full control over type, count, fields, and format.", Group: "generate"},
	{Command: "generate-batch sample-data-post", Description: "Submit multiple sample-data generation requests in one call.", Group: "generate-batch"},
	{Command: "helicopter lookup-by-icao", Description: "Look up helicopter by ICAO hex code", Group: "helicopter"},
	{Command: "helicopter lookup-by-registration", Description: "Look up helicopter by registration number", Group: "helicopter"},
	{Command: "helicopter lookup-by-serial", Description: "Look up helicopter by manufacturer serial number", Group: "helicopter"},
	{Command: "helicopter manufacturers", Description: "List helicopter manufacturers", Group: "helicopter"},
	{Command: "image-processing image-compress", Description: "Compress an image", Group: "image-processing"},
	{Command: "image-processing image-convert", Description: "Convert image to a different format", Group: "image-processing"},
	{Command: "image-processing image-crop", Description: "Crop an image to a region", Group: "image-processing"},
	{Command: "image-processing image-metadata", Description: "Extract metadata from an image", Group: "image-processing"},
	{Command: "image-processing image-pipeline", Description: "Executes an ordered array of image operations in a single request. Recommended over individual endpoints when multiple operations are needed. Supports resize, compress, convert, crop, and metadata.", Group: "image-processing"},
	{Command: "image-processing image-resize", Description: "Resize an image to specified dimensions", Group: "image-processing"},
	{Command: "image-processing info", Description: "Returns supported image operations, formats, and service metadata.", Group: "image-processing"},
	{Command: "ip-geolocation batch", Description: "Batch IP geolocation lookup", Group: "ip-geolocation"},
	{Command: "ip-geolocation get", Description: "Returns country, region, city, coordinates, ISP, ASN, and timezone for any IPv4 or IPv6 address.", Group: "ip-geolocation"},
	{Command: "ip-geolocation post", Description: "Get geographic location for an IP address (POST)", Group: "ip-geolocation"},
	{Command: "ip-intelligence batch", Description: "Batch IP threat intelligence lookup", Group: "ip-intelligence"},
	{Command: "ip-intelligence batch-info", Description: "Returns batch processing limits, example request shape, and response schema details.", Group: "ip-intelligence"},
	{Command: "ip-intelligence get", Description: "Returns trust score, risk classification, VPN/proxy/Tor detection, datacenter detection, and threat categories. Omit the ip parameter to analyze the caller's IP.", Group: "ip-intelligence"},
	{Command: "mac-address lookup", Description: "Lookup vendor by full MAC address, 6-character OUI prefix, or organization name. Provide exactly one of the three parameters.", Group: "mac-address"},
	{Command: "mx-lookup batch", Description: "Batch MX record lookup for multiple domains", Group: "mx-lookup"},
	{Command: "mx-lookup get", Description: "Returns mail exchange records with optional IP resolution, SMTP testing, and SPF extraction.", Group: "mx-lookup"},
	{Command: "mx-lookup post", Description: "Look up MX records for a domain (POST)", Group: "mx-lookup"},
	{Command: "precious-metals assets", Description: "Returns metadata for all supported assets — gold (XAU), silver (XAG), palladium (XPD), copper, BTC, ETH, etc.", Group: "precious-metals"},
	{Command: "precious-metals history", Description: "Get historical price data for an asset", Group: "precious-metals"},
	{Command: "precious-metals prices", Description: "Get current prices for precious metals and crypto", Group: "precious-metals"},
	{Command: "profanity analyze", Description: "Comprehensive profanity analysis with severity and word positions", Group: "profanity"},
	{Command: "profanity detect", Description: "Detect whether text contains profanity", Group: "profanity"},
	{Command: "profanity filter", Description: "Replaces profane words with asterisks. Returns cleaned text.", Group: "profanity"},
	{Command: "public-holidays countries", Description: "List all supported countries for holiday data", Group: "public-holidays"},
	{Command: "public-holidays public_holidays", Description: "Accepts ISO-2, ISO-3, or full country names. Returns holidays with ISO, US, and EU date formats. Filter by year and/or month.", Group: "public-holidays"},
	{Command: "sample-data batch-get", Description: "Generates mock data using Faker.js. Supports 20+ schema types including user, person, address, company, product, and more. Use the requests parameter as a JSON-encoded array.", Group: "sample-data"},
	{Command: "sample-data batch-post", Description: "Generate multiple types of sample data (POST)", Group: "sample-data"},
	{Command: "sample-data generate-get", Description: "GET-compatible sample data generation endpoint for scripts and browser testing.", Group: "sample-data"},
	{Command: "schemas sample-data", Description: "Returns all available sample-data schema names with default field lists.", Group: "schemas"},
	{Command: "secure-relay custom", Description: "Legacy relay endpoint with extended configuration options for custom header injection and response transformation.", Group: "secure-relay"},
	{Command: "secure-relay relay", Description: "Forwards HTTP requests to HTTPS targets with no server-side storage. Requests must include HMAC-SHA256 signature headers for verification. Supports replay attack protection via timestamp validation.", Group: "secure-relay"},
	{Command: "spell-check batch", Description: "Spell check multiple texts", Group: "spell-check"},
	{Command: "spell-check languages", Description: "List supported languages for spell checking", Group: "spell-check"},
	{Command: "spell-check spell_check", Description: "Detects spelling errors with ranked correction suggestions. Supports English, Spanish, French, German, and Italian. Also catches grammar patterns such as repeated words and spacing errors.", Group: "spell-check"},
	{Command: "states by-abbr", Description: "Get U.S. state by 2-letter abbreviation", Group: "states"},
	{Command: "states by-fips", Description: "Get U.S. state by FIPS code", Group: "states"},
	{Command: "states list", Description: "List or search U.S. states", Group: "states"},
	{Command: "text-language detect", Description: "Identifies the language of text with a confidence score. Supports 176+ languages with ISO 639-3 output. Requires at least 10 characters for reliable detection.", Group: "text-language"},
	{Command: "text-language detect-batch", Description: "Batch language detection for multiple texts", Group: "text-language"},
	{Command: "text-language supported", Description: "Returns all 176+ supported languages with ISO 639-1 and ISO 639-3 codes.", Group: "text-language"},
	{Command: "thesaurus lookup", Description: "Returns synonyms, antonyms, or both for a given word. Filter results by part of speech and limit the number of results.", Group: "thesaurus"},
	{Command: "unit-conversion unit-categories", Description: "List available measurement categories", Group: "unit-conversion"},
	{Command: "unit-conversion unit-convert-get", Description: "Supports 100+ unit types across length, weight, temperature, volume, area, speed, digital storage, and time. Converts value from source unit to target unit.", Group: "unit-conversion"},
	{Command: "unit-conversion unit-convert-post", Description: "Convert a value between units (POST)", Group: "unit-conversion"},
	{Command: "unit-conversion units-by-category", Description: "List units available in a category", Group: "unit-conversion"},
	{Command: "user-avatar generate", Description: "Creates avatar images using Canvas (PNG/WebP) or native SVG. Supports initials-based avatars, custom colors, external image integration, and uploaded icons.", Group: "user-avatar"},
	{Command: "user-avatar upload-icon", Description: "Upload a custom icon for avatar generation", Group: "user-avatar"},
	{Command: "validate-ip get", Description: "Validates IPv4, IPv6, or CIDR notation and returns classification flags: private, reserved, loopback, multicast, link-local, bogon, and public. Supports comma-separated batch input (max 100).", Group: "validate-ip"},
	{Command: "validate-ip post", Description: "Validate and classify IP addresses (POST)", Group: "validate-ip"},
	{Command: "vin-lookup vin-decode", Description: "Decodes 17-character Vehicle Identification Numbers using the official NHTSA vPIC database. Validates ISO 3779 check digit. Supports single VIN or batch array (max 50).", Group: "vin-lookup"},
	{Command: "vin-lookup vin-makes", Description: "List all vehicle makes in the NHTSA database", Group: "vin-lookup"},
	{Command: "vin-lookup vin-sample-get", Description: "Decode a single VIN via GET", Group: "vin-lookup"},
	{Command: "vin-lookup vin-suggest", Description: "Get VIN prefix suggestions for autocomplete", Group: "vin-lookup"},
	{Command: "web-screenshot web_screenshot", Description: "Renders a web page via Puppeteer headless browser and returns a screenshot. Supports viewport simulation, format selection, quality control, and crop.", Group: "web-screenshot"},
	{Command: "whois lookup", Description: "Returns registrar, registration date, expiration date, name servers, and raw WHOIS data. Supports single domain or batch array (max 50).", Group: "whois"},
	{Command: "working-days batch", Description: "Batch working day calculations", Group: "working-days"},
	{Command: "working-days calculate-get", Description: "Calculate working days (GET)", Group: "working-days"},
	{Command: "working-days calculate-post", Description: "For range calculations: provide start_date and end_date to get the number of working days between them. For offset calculations: provide start_date and days_offset to find the resulting business date. Supports US, DE, and IN regional holiday calendars.", Group: "working-days"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  datpaq which "stale tickets"
  datpaq which "bottleneck"
  datpaq which --limit 1 "send message"
  datpaq which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
