// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWorkingDaysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "working-days",
		Short:  "Business day calculations with regional holiday support",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWorkingDaysBatchCmd(flags))
	cmd.AddCommand(newWorkingDaysCalculateGetCmd(flags))
	cmd.AddCommand(newWorkingDaysCalculatePostCmd(flags))
	return cmd
}
