// Copyright 2026 datpaq. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	_ "modernc.org/sqlite"
)

// TestStoreWrite_NoSQLITE_BUSY_HighConcurrency exercises the writeMu serialization
// guarantee: 16 fetcher-style goroutines hammer the store with a mix of
// UpsertBatch, SaveSyncState, and SaveSyncCursor calls. Before the mutex
// fix, this test reproduces SQLITE_BUSY at default sync concurrency on
// pure-Go SQLite (modernc.org/sqlite + WAL) because multiple writers
// race for the WAL lock and busy_timeout retries are not exhaustive.
//
// Run under `go test -race` to catch any data races on Store fields.
func TestStoreWrite_NoSQLITE_BUSY_HighConcurrency(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	const goroutines = 16
	const itemsPerBatch = 5

	var wg sync.WaitGroup
	errCh := make(chan error, goroutines*3)

	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(gid int) {
			defer wg.Done()
			rt := fmt.Sprintf("rt_%d", gid)
			items := make([]json.RawMessage, 0, itemsPerBatch)
			for i := 0; i < itemsPerBatch; i++ {
				items = append(items, json.RawMessage(fmt.Sprintf(`{"id": "g%d-i%d"}`, gid, i)))
			}
			if _, _, err := s.UpsertBatch(rt, items); err != nil {
				errCh <- fmt.Errorf("UpsertBatch goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncState(rt, fmt.Sprintf("cursor-%d", gid), itemsPerBatch); err != nil {
				errCh <- fmt.Errorf("SaveSyncState goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncCursor(rt, fmt.Sprintf("cursor2-%d", gid)); err != nil {
				errCh <- fmt.Errorf("SaveSyncCursor goroutine %d: %w", gid, err)
				return
			}
		}(g)
	}
	wg.Wait()
	close(errCh)

	for err := range errCh {
		if err == nil {
			continue
		}
		// SQLITE_BUSY surfaces as "database is locked" or "SQLITE_BUSY"
		// in the error message — assert neither occurs.
		msg := err.Error()
		if strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(strings.ToLower(msg), "database is locked") {
			t.Fatalf("got SQLITE_BUSY-class error under concurrent writers: %v", err)
		}
		t.Fatalf("unexpected error under concurrent writers: %v", err)
	}

	// Verify all rows persisted: goroutines * itemsPerBatch in the generic
	// resources table.
	db := s.DB()
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&total); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if total != goroutines*itemsPerBatch {
		t.Fatalf("resources total = %d, want %d", total, goroutines*itemsPerBatch)
	}
}

// TestStoreWrite_PanicReleasesLock confirms that a panic inside a locked
// section unwinds via defer s.writeMu.Unlock() so subsequent writers can
// proceed. A leaked lock would deadlock the second call indefinitely.
func TestStoreWrite_PanicReleasesLock(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Trigger panic by passing a nil *Store method receiver indirectly:
	// we call UpsertBatch with malformed JSON that survives Unmarshal
	// (it's wrapped in skipped-count handling) — there's no easy panic
	// path inside a locked section that doesn't also corrupt state, so
	// we instead simulate the post-panic state by manually locking and
	// unlocking, then assert subsequent calls succeed.
	func() {
		defer func() {
			recover()
		}()
		s.writeMu.Lock()
		defer s.writeMu.Unlock()
		panic("simulated writer panic")
	}()

	// Subsequent writer must not block.
	done := make(chan struct{})
	go func() {
		if _, _, err := s.UpsertBatch("post_panic", []json.RawMessage{json.RawMessage(`{"id": "x"}`)}); err != nil {
			t.Errorf("post-panic UpsertBatch: %v", err)
		}
		close(done)
	}()
	<-done
}

// TestUpsertBatch_TemplatedIDFieldOverrideWins exercises the
// per-resource ID-field override. When the spec author annotates a
// path-item with x-resource-id, the profiler emits SyncableResource.IDField,
// the generator templates this into resourceIDFieldOverrides, and
// UpsertBatch consults that map first. This test seeds the override map
// at runtime (since the generated table here may or may not declare any
// override) to assert the lookup path itself works.
func TestUpsertBatch_TemplatedIDFieldOverrideWins(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Inject a runtime override for a synthetic resource. Item carries
	// no generic-fallback field (no id/name/uuid/...) — only a custom
	// "ticker" field. Without the override, all 3 items would be
	// dropped as PK-unresolved; with it, all 3 land.
	prev, hadPrev := resourceIDFieldOverrides["overrideTest"]
	resourceIDFieldOverrides["overrideTest"] = "ticker"
	defer func() {
		if hadPrev {
			resourceIDFieldOverrides["overrideTest"] = prev
		} else {
			delete(resourceIDFieldOverrides, "overrideTest")
		}
	}()

	items := []json.RawMessage{
		json.RawMessage(`{"ticker": "AAPL", "price": 100}`),
		json.RawMessage(`{"ticker": "GOOG", "price": 200}`),
		json.RawMessage(`{"ticker": "MSFT", "price": 300}`),
	}
	stored, extractFailures, err := s.UpsertBatch("overrideTest", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 3 {
		t.Fatalf("stored = %d, want 3 (templated override should resolve all PKs)", stored)
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}
}

// TestUpsertBatch_GenericFallbackList covers each name in the reduced
// fallback list. The kalshi-accreted names (ticker/event_ticker/series_ticker)
// were dropped because the user owns kalshi and will regenerate
// it with x-resource-id annotations; this test pins what the generic list
// is now responsible for so a future trim doesn't silently break unannotated
// specs.
func TestUpsertBatch_GenericFallbackList(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	for _, key := range []string{"id", "ID", "gid", "sid", "uid", "uuid", "guid", "name", "slug", "key", "code"} {
		t.Run(key, func(t *testing.T) {
			rt := "fallback_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-1")),
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-2")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 2 {
				t.Fatalf("stored = %d, want 2 (fallback %q must resolve)", stored, key)
			}
			if extractFailures != 0 {
				t.Fatalf("extractFailures = %d, want 0", extractFailures)
			}
		})
	}

	// Negative: API-specific names dropped must NOT resolve.
	// Spec authors annotate these via x-resource-id instead.
	for _, key := range []string{"ticker", "event_ticker", "series_ticker"} {
		t.Run("dropped_"+key, func(t *testing.T) {
			rt := "dropped_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "v1")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 0 {
				t.Fatalf("stored = %d, want 0 (%q must NOT be in the generic fallback list)", stored, key)
			}
			if extractFailures != 1 {
				t.Fatalf("extractFailures = %d, want 1 (%q drop must surface as extract failure)", extractFailures, key)
			}
		})
	}
}

// TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses pins the third
// return value: items that survive JSON unmarshal but have no extractable
// PK (templated override AND generic fallback both miss) bump
// extractFailures. The sync.go.tmpl call site uses this to emit the
// per-resource primary_key_unresolved sync_anomaly the first time silent
// drops occur.
func TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ok-1"}`),
		json.RawMessage(`{"some_random_field": "no-pk-here"}`),
		json.RawMessage(`{"id": "ok-2"}`),
		json.RawMessage(`{"another_field": 42}`),
	}
	stored, extractFailures, err := s.UpsertBatch("mixed_extraction", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 2 {
		t.Fatalf("stored = %d, want 2 (only items with id should land)", stored)
	}
	if extractFailures != 2 {
		t.Fatalf("extractFailures = %d, want 2 (two items have no extractable PK)", extractFailures)
	}
}

// TestUpsertBatch_PopulatesAircraftTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed aircraft table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAircraftTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("aircraft", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "aircraft").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "aircraft")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count aircraft: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("aircraft count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesCountryCodesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed country_codes table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesCountryCodesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("country-codes", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "country-codes").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "country_codes")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count country_codes: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("country_codes count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesDomainLookupTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed domain_lookup table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDomainLookupTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("domain-lookup", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "domain-lookup").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "domain_lookup")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count domain_lookup: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("domain_lookup count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesEmailValidationTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed email_validation table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEmailValidationTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("email-validation", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "email-validation").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "email_validation")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count email_validation: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("email_validation count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesEvChargerTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed ev_charger table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEvChargerTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("ev-charger", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "ev-charger").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "ev_charger")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count ev_charger: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("ev_charger count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesExchangeRatesAndCurrencyTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed exchange_rates_and_currency table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesExchangeRatesAndCurrencyTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("exchange-rates-and-currency", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "exchange-rates-and-currency").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "exchange_rates_and_currency")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count exchange_rates_and_currency: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("exchange_rates_and_currency count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesHelicopterTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed helicopter table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesHelicopterTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("helicopter", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "helicopter").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "helicopter")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count helicopter: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("helicopter count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesImageProcessingTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed image_processing table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesImageProcessingTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("image-processing", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "image-processing").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "image_processing")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count image_processing: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("image_processing count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesIpGeolocationTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed ip_geolocation table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesIpGeolocationTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("ip-geolocation", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "ip-geolocation").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "ip_geolocation")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count ip_geolocation: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("ip_geolocation count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesIpIntelligenceTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed ip_intelligence table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesIpIntelligenceTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("ip-intelligence", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "ip-intelligence").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "ip_intelligence")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count ip_intelligence: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("ip_intelligence count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesMxLookupTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed mx_lookup table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesMxLookupTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("mx-lookup", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "mx-lookup").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "mx_lookup")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count mx_lookup: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("mx_lookup count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesPreciousMetalsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed precious_metals table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPreciousMetalsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("precious-metals", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "precious-metals").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "precious_metals")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count precious_metals: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("precious_metals count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesProfanityTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed profanity table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesProfanityTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("profanity", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "profanity").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "profanity")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count profanity: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("profanity count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesPublicHolidaysTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed public_holidays table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPublicHolidaysTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("public-holidays", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "public-holidays").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "public_holidays")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count public_holidays: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("public_holidays count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesSampleDataTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed sample_data table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSampleDataTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("sample-data", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "sample-data").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "sample_data")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count sample_data: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("sample_data count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesSecureRelayTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed secure_relay table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSecureRelayTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("secure-relay", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "secure-relay").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "secure_relay")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count secure_relay: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("secure_relay count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesSpellCheckTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed spell_check table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSpellCheckTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("spell-check", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "spell-check").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "spell_check")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count spell_check: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("spell_check count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesStatesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed states table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesStatesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("states", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "states").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "states")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count states: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("states count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTextLanguageTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed text_language table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTextLanguageTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("text-language", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "text-language").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "text_language")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count text_language: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("text_language count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesUnitConversionTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed unit_conversion table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesUnitConversionTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("unit-conversion", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "unit-conversion").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "unit_conversion")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count unit_conversion: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("unit_conversion count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesUserAvatarTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed user_avatar table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesUserAvatarTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("user-avatar", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "user-avatar").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "user_avatar")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count user_avatar: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("user_avatar count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesValidateIpTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed validate_ip table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesValidateIpTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("validate-ip", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "validate-ip").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "validate_ip")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count validate_ip: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("validate_ip count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesVinLookupTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed vin_lookup table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesVinLookupTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("vin-lookup", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "vin-lookup").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "vin_lookup")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count vin_lookup: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("vin_lookup count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesWorkingDaysTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed working_days table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesWorkingDaysTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("working-days", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "working-days").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "working_days")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count working_days: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("working_days count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}
